import type { 
  ChartType,
  ThemePalette, 
  MetricMode, 
  SunburstLevelConfig,
  DecimalPrecision,
  RatioStyle,
  DisplayFormatTemplate,
  AxisLocation,
  AxisLabelFormat,
  AxisGridLineStyle,
  AxisFontWeight,
  AxisFontStyle
} from '../types';
import { formatMetricDisplay } from '../utils/formatterUtils';

export interface ChartGeneratorContext {
  chartType?: ChartType;
  papers: any[];
  palette: ThemePalette;
  font: string;
  fontSize: number;
  baseTitle: any;
  baseLegend: any;
  baseTooltip: any;
  renderCategoryTooltip: (dataObj: any, fallbackName?: string) => string;
  primaryField: string;
  secondaryField: string;
  metricMode: MetricMode;
  sankeyFields: string[];
  sankeyLabelPositions: Record<number, 'left' | 'right'>;
  sankeyMaxNodes: Record<number, number>;
  tailLabelStyle?: 'comma_list' | 'other_count' | 'other_items' | 'plain_other';
  limitCategories: boolean;
  maxCategoriesCount: number;
  numFieldX: string;
  numFieldY: string;
  numFieldSize: string;
  useUmbrellanizer: boolean;
  splitMultiValues: boolean;
  excludeEmpty: boolean;
  showDataLabels: boolean;
  labelRotation: number;
  donutRatio: number;
  smoothLine: boolean;
  sankeyNodeWidth: number;
  sankeyNodeGap: number;
  sankeyLeftPadding: number;
  sankeyRightPadding: number;
  sankeyTopPadding?: number;
  sankeyBottomPadding?: number;
  sankeyOrient?: 'horizontal' | 'vertical';
  sankeyNodeAlign?: 'justify' | 'left' | 'right';
  sankeyCurveness?: number;
  sankeyLinkColorMode?: 'gradient' | 'source' | 'target';
  sankeyLinkOpacity?: number;
  sankeyNodeBorderRadius?: number;
  sankeyNodeBorderWidth?: number;
  sankeyLayoutIterations?: number;
  sankeyDraggable?: boolean;
  sankeyLabelPosition?: 'auto' | 'left' | 'right' | 'inside' | 'top' | 'bottom';
  sankeyLabelDistance?: number;
  sankeyLabelOverflow?: 'break' | 'truncate' | 'none';
  sankeyMaxLabelWidth?: number;
  sankeyLabelFontSize?: number;
  sankeyLabelRotate?: number;
  sankeyEmphasisFocus?: 'adjacency' | 'trajectory' | 'series' | 'none';
  sankeyLevelLabelFormats?: Record<number, DisplayFormatTemplate>;
  sankeyLevelNodeGaps?: Record<number, number>;
  sankeyLevelLabelDistances?: Record<number, number>;
  sankeyLevelNodeWidths?: Record<number, number>;
  sankeyLevelPathFilters?: Record<number, string>;
  sankeySort?: 'desc' | 'asc' | 'alpha' | 'none';
  sankeyLabelLineHeight?: number;
  sankeyLabelFontWeight?: 'normal' | 'bold' | '500' | '600' | '700' | '800';
  sankeyLabelColor?: string;
  bubbleScale: number;
  gaugeMaxScale: number;
  sunburstLevelConfigs: Record<number, SunburstLevelConfig>;
  sunburstSort: 'desc' | 'asc' | 'none';
  sunburstNodeClick: 'rootToNode' | 'link' | 'none';
  sunburstEmphasisFocus: 'ancestor' | 'descendant' | 'none';
  barSorting: 'desc' | 'asc' | 'none';
  barOrientation?: 'horizontal' | 'vertical';
  barThickness: number;
  barBorderRadius: number;
  barGap: number;
  barClusterGap?: number;
  barInnerGap?: number;
  enableErrorBars?: boolean;
  errorBarType?: 'std_dev' | 'std_error' | 'ci_95';
  enableHatchPatterns?: boolean;
  axisScaleType?: 'linear' | 'log';
  axisTickDirection?: 'inside' | 'outside' | 'none';
  showAxisBaseline?: boolean;
  customAxisTitleX?: string;
  customAxisTitleY?: string;
  showAxisTitleX?: boolean;
  showAxisTitleY?: boolean;
  axisTitleFontSizeX?: number;
  axisTitleFontSizeY?: number;
  axisTitleFontWeightX?: AxisFontWeight;
  axisTitleFontWeightY?: AxisFontWeight;
  axisTitleFontStyleX?: AxisFontStyle;
  axisTitleFontStyleY?: AxisFontStyle;
  axisTitleColorX?: string;
  axisTitleColorY?: string;
  axisTitleLocationX?: AxisLocation;
  axisTitleLocationY?: AxisLocation;
  axisTitleGapX?: number;
  axisTitleGapY?: number;
  showAxisLabelX?: boolean;
  showAxisLabelY?: boolean;
  axisLabelFontSizeX?: number;
  axisLabelFontSizeY?: number;
  axisLabelFontWeightX?: AxisFontWeight;
  axisLabelFontWeightY?: AxisFontWeight;
  axisLabelFontStyleX?: AxisFontStyle;
  axisLabelFontStyleY?: AxisFontStyle;
  axisLabelColorX?: string;
  axisLabelColorY?: string;
  axisLabelRotateX?: number;
  axisLabelRotateY?: number;
  axisLabelMarginX?: number;
  axisLabelMarginY?: number;
  axisLabelOverflowX?: 'none' | 'truncate' | 'break';
  axisLabelOverflowY?: 'none' | 'truncate' | 'break';
  axisLabelWidthX?: number;
  axisLabelWidthY?: number;
  axisLabelLineHeightX?: number;
  axisLabelLineHeightY?: number;
  axisLabelFormatX?: AxisLabelFormat;
  axisLabelFormatY?: AxisLabelFormat;
  axisLabelPrefixX?: string;
  axisLabelSuffixX?: string;
  axisLabelPrefixY?: string;
  axisLabelSuffixY?: string;
  axisLabelIntervalX?: 'auto' | number;
  axisLabelIntervalY?: 'auto' | number;
  showGridLinesX?: boolean;
  showGridLinesY?: boolean;
  gridLineStyle?: AxisGridLineStyle;
  gridLineColor?: string;
  gridLineOpacity?: number;
  labelFormat?: DisplayFormatTemplate;
  barLabelPosition: 'right' | 'inside' | 'insideLeft' | 'insideRight';
  barLabelFormat: DisplayFormatTemplate;
  barYAxisWidth: number;
  barYAxisOverflow: 'break' | 'truncate' | 'none';
  barLineHeight?: number;
  barYAxisFontSize?: number;
  barYAxisFontWeight?: AxisFontWeight;
  barYAxisFontStyle?: AxisFontStyle;
  barYAxisColor?: string;
  barBenchmarkLine: boolean;
  barBenchmarkValue: number;
  barBenchmarkLabel: string;
  barBenchmarkStyle: 'dashed' | 'solid';
  barBenchmarkColor: string;
  legendFormat?: DisplayFormatTemplate;
  barLegendFormat: DisplayFormatTemplate;
  barLegendPosition: 'top-left' | 'top-center' | 'top-right' | 'left' | 'right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
  decimalPrecision?: DecimalPrecision;
  useTildeForCoarse?: boolean;
  ratioStyle?: RatioStyle;
  forceCohortDenominator?: boolean;
  chartScale: number;
  panX: number;
  panY: number;
  tiltAngle: number;
  rotationAngle: number;
  showLegend: boolean;
  legendPosition?: 'top' | 'bottom' | 'left' | 'right';
  sunburstLegendLevel: number;
  sunburstLegendFormat: DisplayFormatTemplate;
  sunburstLegendPosition: 'top-left' | 'top-center' | 'top-right' | 'left' | 'right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
  levelCustomGroups: Record<number, string[]>;
  levelCustomGroupLinks: Record<number, Record<string, string>>;
  levelTargetFields?: Record<number, string>;
  primaryScopeFilter?: string;
  secondaryScopeFilter?: string;
  customCategoryMap: Record<string, Record<string, string>>;
  enableManualOverrides: boolean;
  manualCategoryValues: Record<string, number>;
  customSliceColors: Record<string, string>;
  pieLabelPlacement?: 'outside' | 'inside' | 'legend_only' | 'edge_aligned';
  pieRadiusRatio?: number;
  pieLabelWidth?: number;
  pieLeaderLineLength?: number;
  pieLeaderLineLength2?: number;
  pieLabelDistance?: number;
  pieLabelLineHeight?: number;
  pieLineHeight?: number;
  barLabelDistance?: number;
  barLabelFontSize?: number;
  barLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  barLabelFontStyle?: 'normal' | 'italic';
  barLabelColor?: string;
  barLabelRotate?: number;
  barLabelShowZero?: boolean;
  barLabelMinThreshold?: number;
  barLabelLineHeight?: number;
  barValueCeiling?: number | 'auto';
  barValueInterval?: number | 'auto';
  legendDistance?: number;
  legendWidth?: number;
  legendWrapWidth?: number;
  legendLineHeight?: number;
  legendItemGap?: number;
  legendFontSize?: number;
  legendFontStyle?: 'normal' | 'italic';
  legendOverflow?: 'break' | 'truncate' | 'none';
  fitOffsetX?: number;
  fitOffsetY?: number;
  containerPadding?: number;
  umbrellanizerMap?: Record<string, Record<string, string>>;
  // Rich chart customization parameters
  lineMode?: 'cohort_trend' | 'epistemic_simulation';
  lineTimeSteps?: number;
  lineTimeStepIntervalName?: string;
  lineYAxisTitle?: string;
  lineYMin?: number;
  lineYMax?: number;
  lineBaselineA?: number;
  lineBaselineB?: number;
  lineBaselineName?: string;
  lineBaselineColor?: string;
  lineBaselineStyle?: 'solid' | 'dashed' | 'dotted';
  lineEstimatorInitial?: number;
  lineEstimatorDrift?: number;
  lineEstimatorModulation?: number;
  lineEstimatorName?: string;
  lineEstimatorColor?: string;
  lineEstimatorStyle?: 'solid' | 'dashed' | 'dotted';
  lineThresholdValue?: number;
  lineThresholdName?: string;
  lineThresholdLabel?: string;
  lineThresholdColor?: string;
  lineThresholdStyle?: 'dotted' | 'dashed' | 'solid';
  lineThresholdPosition?: 'insideEndTop' | 'insideStartTop' | 'insideMiddleTop' | 'end' | 'start';
  lineThresholdLineWidth?: number;
  lineAxisPointerType?: 'cross' | 'line' | 'shadow';
  lineMarkerSymbol?: 'circle' | 'rect' | 'triangle' | 'diamond' | 'none' | 'emptyCircle';
  lineXAxisInterval?: number | 'auto';
  lineShowGridLines?: boolean;
  lineGridLeft?: number;
  lineGridRight?: number;
  lineGridTop?: number;
  lineGridBottom?: number;
  lineWidth?: number;
  showLineMarkers?: boolean;
  lineMarkerSize?: number;
  lineAreaOpacity?: number;
  lineBaselineAreaOpacity?: number;
  lineEstimatorAreaOpacity?: number;
  lineBaselineFillMode?: 'none' | 'subtle_gradient' | 'solid';
  lineEstimatorFillMode?: 'none' | 'subtle_gradient' | 'solid';
  lineShowTxEvents?: boolean;
  lineTxEventSymbol?: 'triangle' | 'pin' | 'diamond' | 'circle' | 'arrow';
  lineTxEventColor?: string;
  lineTxEventSize?: number;
  lineShowTxLabels?: boolean;
  lineTxEventLabel?: string;
  lineTxEventSeriesName?: string;
  lineStepMode?: 'none' | 'start' | 'middle' | 'end';
  roseType?: 'none' | 'radius' | 'area';
  piePadAngle?: number;
  pieCornerRadius?: number;
  treemapAlgorithm?: 'squarified' | 'sliceAndDice' | 'binary';
  treemapVisibleDepth?: number;
  treemapGapWidth?: number;
  treemapBorderWidth?: number;
  heatmapCellRadius?: number;
  heatmapColorPreset?: 'academic' | 'viridis' | 'plasma' | 'thermal' | 'coolwarm';
  radarShape?: 'polygon' | 'circle';
  radarAreaOpacity?: number;
  radarLineWidth?: number;
  radarSplitNumber?: number;
  radarRadius?: number;
  radarAxisLine?: boolean;
  radarSplitLine?: boolean;
  radarSplitArea?: boolean;
  radarAxisNameMargin?: number;
  radarAxisNameWidth?: number;
  radarAxisNameOverflow?: 'break' | 'truncate' | 'none';
  radarAxisNameLineHeight?: number;
  radarShowDataLabels?: boolean;
  radarDataLabelPosition?: 'top' | 'bottom' | 'inside' | 'outside' | 'auto';
  radarBaselineLineStyle?: 'solid' | 'dashed' | 'dotted';
  radarBaselineSymbol?: 'circle' | 'rect' | 'triangle' | 'diamond' | 'none';
  radarBaselineSymbolSize?: number;
  radarMode?: 'multi_variable' | 'qa_breakdown';
  radarVariables?: string[];
  radarVariableAliases?: Record<string, string>;
  radarVariableTargets?: Record<string, number>;
  radarIndicatorFormat?: 'two_line' | 'single_line' | 'ratio_percent' | 'name_only';
  radarShowTarget?: boolean;
  radarTargetName?: string;
  radarTargetValue?: number;
  radarTargetLineStyle?: 'dashed' | 'solid' | 'dotted';
  radarTargetLineWidth?: number;
  radarTargetColor?: string;
  radarTargetAreaOpacity?: number;
  radarTargetSymbol?: 'circle' | 'rect' | 'triangle' | 'diamond' | 'none';
  radarTargetSymbolSize?: number;
  radarBaselineName?: string;
  radarBaselineColor?: string;
  funnelAlign?: 'center' | 'left' | 'right';
  funnelGap?: number;
  funnelNeckWidth?: number;
  funnelNeckHeight?: number;
  boxplotBoxWidth?: number;
  boxplotShowScatter?: boolean;
  boxplotOrientation?: 'vertical' | 'horizontal';
  scatterPointSize?: number;
  scatterPointOpacity?: number;
  scatterShowRegression?: boolean;
  scatterRegressionType?: 'linear' | 'mean';
  bubbleMode?: 'categorical_matrix' | 'numerical_3d';
  bubbleMinRadius?: number;
  bubbleMaxRadius?: number;
  bubbleOpacity?: number;
  bubbleBorderWidth?: number;
  bubbleBorderColor?: string;
  bubbleShowLabels?: boolean;
  bubbleLabelFormat?: 'count_n' | 'count_only' | 'percent' | 'label';
  bubbleLabelFontSize?: number;
  bubbleLabelColor?: string;
  bubbleColorMode?: 'color_by_x' | 'color_by_y' | 'color_by_metric' | 'custom_compliance';
  bubbleShowGridLines?: boolean;
  bubbleComplianceRules?: Record<string, { label?: string; compliance?: string; color?: string }>;
  bubbleXAxisName?: string;
  bubbleYAxisName?: string;
  bubbleXAxisNameGap?: number;
  bubbleYAxisNameGap?: number;
  bubbleXAxisNameLocation?: 'middle' | 'start' | 'end';
  bubbleYAxisNameLocation?: 'middle' | 'start' | 'end';
  bubbleAxisTitleFontSize?: number;
  bubbleAxisTitleFontWeight?: 'bold' | 'normal' | 'bolder';
  bubbleAxisTitleColor?: string;
  bubbleGridLeft?: number;
  bubbleGridBottom?: number;
  bubbleGridTop?: number;
  bubbleGridRight?: number;
  bubbleSeriesName?: string;
  bubbleLegendMode?: 'category_series' | 'single_series' | 'none';
  graphRepulsion?: number;
  graphEdgeLength?: number;
  graphGravity?: number;
  graphCurveness?: number;
  graphShowLinkWeights?: boolean;
  gaugeStartAngle?: number;
  gaugeEndAngle?: number;
  gaugePointerWidth?: number;
  gaugeDialWidth?: number;
  calendarCellSize?: number;
  calendarYear?: string;
  stackedNormalized?: boolean;
  legendType?: 'plain' | 'scroll';
  legendAlign?: 'auto' | 'left' | 'right';
  legendIcon?: 'inherit' | 'circle' | 'rect' | 'roundRect' | 'triangle' | 'diamond' | 'pin' | 'arrow' | 'none' | 'line';
  legendItemWidth?: number;
  legendItemHeight?: number;
  legendFontWeight?: 'normal' | 'bold' | 'bolder' | 'lighter' | number | string;
  legendTextColor?: string;
  legendBackgroundColor?: string;
  legendBorderColor?: string;
  legendBorderWidth?: number;
  legendBorderRadius?: number;
  legendPadding?: number;
  // Dual-Axis & Horizontal Bar + Scatter Combo Parameters
  scatterAxisTitle?: string;
  scatterAxisMin?: number;
  scatterAxisMax?: number;
  scatterAxisInterval?: number;
  scatterAxisNameGap?: number;
  scatterSeriesName?: string;
  barSeriesName?: string;
  scatterSymbol?: 'diamond' | 'circle' | 'rect' | 'triangle' | 'pin' | 'roundRect';
  scatterSymbolSize?: number;
  scatterColor?: string;
  scatterBorderColor?: string;
  scatterBorderWidth?: number;
  scatterValues?: Record<string, number>;
  scatterShowDataLabels?: boolean;
  scatterLabelPosition?: 'top' | 'bottom' | 'right' | 'left' | 'inside';
  scatterLabelFontSize?: number;
  scatterLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  scatterLabelFontStyle?: 'normal' | 'italic';
  scatterLabelColor?: string;
  scatterLabelDistance?: number;
  scatterLabelLineHeight?: number;
  lineLabelFontSize?: number;
  lineLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  lineLabelFontStyle?: 'normal' | 'italic';
  lineLabelColor?: string;
  pieLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  pieLabelFontStyle?: 'normal' | 'italic';
  pieLabelColor?: string;
  radarLabelFontSize?: number;
  radarLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  radarLabelFontStyle?: 'normal' | 'italic';
  radarLabelColor?: string;
  heatmapLabelFontSize?: number;
  heatmapLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  heatmapLabelFontStyle?: 'normal' | 'italic';
  heatmapLabelColor?: string;
  treemapLabelFontSize?: number;
  treemapLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  treemapLabelFontStyle?: 'normal' | 'italic';
  treemapLabelColor?: string;
  funnelLabelFontSize?: number;
  funnelLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  funnelLabelFontStyle?: 'normal' | 'italic';
  funnelLabelColor?: string;
  boxplotLabelFontSize?: number;
  boxplotLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  boxplotLabelFontStyle?: 'normal' | 'italic';
  boxplotLabelColor?: string;
  bubbleLabelFontWeight?: 'normal' | '500' | '600' | 'bold' | '800';
  bubbleLabelFontStyle?: 'normal' | 'italic';
  barColorCustom?: string;
  barGridTop?: number;
  barGridBottom?: number;
  barGridLeft?: number;
  barGridRight?: number;
  scatterSortMode?: 'prevalence_desc' | 'prevalence_asc' | 'scatter_desc' | 'scatter_asc' | 'alpha' | 'dataset';
  otherCategoryLabel?: string;
}

export function formatLegendLabel(
  name: string,
  stats: { 
    paperCount?: number; 
    tagCount?: number;
    count?: number;
    percent?: number | string; 
    prevalencePct?: number | string; 
    tagSharePct?: number | string;
    totalCohortPapers?: number;
    totalExtractedTags?: number;
    metricMode?: MetricMode;
    decimalPrecision?: DecimalPrecision;
    useTildeForCoarse?: boolean;
    ratioStyle?: RatioStyle;
    forceCohortDenominator?: boolean;
  },
  format: DisplayFormatTemplate = 'name'
): string {
  return formatMetricDisplay({
    name,
    paperCount: stats.paperCount,
    tagCount: stats.tagCount,
    count: stats.count,
    totalCohortPapers: stats.totalCohortPapers,
    totalExtractedTags: stats.totalExtractedTags,
    metricMode: stats.metricMode,
    prevalencePct: stats.prevalencePct,
    tagSharePct: stats.tagSharePct,
    activePct: stats.percent,
    template: format,
    decimalPrecision: stats.decimalPrecision ?? 0,
    useTildeForCoarse: stats.useTildeForCoarse ?? true,
    ratioStyle: stats.ratioStyle ?? 'n_over_N',
    forceCohortDenominator: stats.forceCohortDenominator ?? false
  });
}

