import type { SunburstLevelConfig, TreemapLevelConfig, SlotConfig, SlotId } from '../types';

export const CUSTOM_GROUPING_KEY = '__custom_grouping__';
export const CUSTOM_GROUPING_LABEL = '✨ [Custom Grouping Layer]';

export const DEFAULT_SUNBURST_LEVEL_CONFIGS: Record<number, SunburstLevelConfig> = {
  0: { r0: 15, r: 40, position: 'inside', rotate: 'tangential', align: 'center', minAngle: 0, borderWidth: 2, borderRadius: 0, fontSize: 12, fontWeight: 'bold', fontStyle: 'normal', colorMode: 'auto_contrast', overflow: 'break', maxLabelWidth: 85, labelFormat: 'name', hideOverlap: true },
  1: { r0: 40, r: 75, position: 'inside', rotate: 'radial', align: 'center', minAngle: 3, borderWidth: 1, borderRadius: 0, fontSize: 10, fontWeight: '600', fontStyle: 'normal', colorMode: 'auto_contrast', overflow: 'truncate', maxLabelWidth: 70, labelFormat: 'name', hideOverlap: true },
  2: { r0: 75, r: 77, position: 'outside', rotate: 'radial', align: 'right', minAngle: 4, borderWidth: 2, borderRadius: 0, fontSize: 9, fontWeight: 'normal', fontStyle: 'normal', colorMode: 'auto_contrast', overflow: 'truncate', maxLabelWidth: 60, labelFormat: 'name', hideOverlap: true }
};

export const DEFAULT_TREEMAP_LEVEL_CONFIGS: Record<number, TreemapLevelConfig> = {
  0: { gapWidth: 3, borderWidth: 2, borderRadius: 0, visibleMin: 10, childrenVisibleMin: 0 },
  1: { gapWidth: 2, borderWidth: 1, borderRadius: 0, visibleMin: 10, childrenVisibleMin: 0 },
  2: { gapWidth: 1, borderWidth: 1, borderRadius: 0, visibleMin: 5, childrenVisibleMin: 0 }
};

export const DEFAULT_CUSTOM_GROUPS: Record<number, string[]> = {};

export const DEFAULT_CUSTOM_GROUP_LINKS: Record<number, Record<string, string>> = {};

export const DEFAULT_LEVEL_TARGET_FIELDS: Record<number, string> = {};

export function createDefaultSlotConfig(slotId: SlotId): SlotConfig {
  const isSlotA = slotId === 'slot_a';
  const isSlotB = slotId === 'slot_b';
  const isSlotC = slotId === 'slot_c';

  return {
    chartType: isSlotA ? 'bar_vertical' : isSlotB ? 'sunburst' : isSlotC ? 'line' : 'pie_donut',
    subTitle: isSlotA ? 'Distribution Overview' : isSlotB ? 'Hierarchical Taxonomy' : isSlotC ? 'Temporal Trend' : 'Proportional Share',
    primaryField: isSlotA ? 'Year' : isSlotB ? CUSTOM_GROUPING_KEY : isSlotC ? 'Year' : 'Import_Source',
    secondaryField: isSlotA ? 'Import_Source' : 'Local_PDF_Status',
    metricMode: 'count',
    sankeyFields: ['Year', 'Import_Source', 'Local_PDF_Status'],
    sankeyLabelPositions: {},
    sankeyMaxNodes: {},
    tailLabelStyle: 'comma_list',
    limitCategories: false,
    maxCategoriesCount: 10,
    numFieldX: 'Overall_QA',
    numFieldY: 'citation_count',
    numFieldSize: 'Year',
    useUmbrellanizer: true,
    splitMultiValues: true,
    excludeEmpty: true,
    showLegend: true,
    legendPosition: 'top',
    showDataLabels: true,
    labelRotation: 0,
    donutRatio: 50,
    smoothLine: true,
    sankeyNodeWidth: 20,
    sankeyNodeGap: 18,
    sankeyLeftPadding: 8,
    sankeyRightPadding: 20,
    sankeyTopPadding: 12,
    sankeyBottomPadding: 8,
    sankeyOrient: 'horizontal',
    sankeyNodeAlign: 'justify',
    sankeyCurveness: 0.5,
    sankeyLinkColorMode: 'gradient',
    sankeyLinkOpacity: 45,
    sankeyNodeBorderRadius: 2,
    sankeyNodeBorderWidth: 1,
    sankeyLayoutIterations: 0,
    sankeyDraggable: true,
    sankeyLabelPosition: 'auto',
    sankeyLabelDistance: 6,
    sankeyLabelOverflow: 'break',
    sankeyMaxLabelWidth: 120,
    sankeyLabelFontSize: undefined,
    sankeyLabelRotate: 0,
    sankeyEmphasisFocus: 'adjacency',
    sankeyLevelLabelFormats: {},
    sankeyLevelNodeGaps: {},
    sankeyLevelLabelDistances: {},
    sankeyLevelNodeWidths: {},
    sankeyLevelPathFilters: {},
    sankeySort: 'desc',
    sankeyPinUnstatedToBottom: true,
    sankeyFlowConservation: true,
    sankeyLevelNodeOrders: {},
    levelSegmentIndices: {},
    levelScopeFilters: {},
    sankeyLabelLineHeight: 14,
    sankeyLabelFontWeight: '600',
    sankeyLabelColor: '',
    bubbleScale: 1.2,
    gaugeMaxScale: 100,
    sunburstLevelConfigs: { ...DEFAULT_SUNBURST_LEVEL_CONFIGS },
    sunburstSort: 'desc',
    sunburstNodeClick: 'rootToNode',
    sunburstEmphasisFocus: 'ancestor',
    sunburstColorMode: 'branch_gradient',
    barSorting: 'desc',
    barOrientation: 'horizontal',
    barThickness: 26,
    barBorderRadius: 4,
    barGap: 24,
    barClusterGap: 20,
    barInnerGap: 15,
    enableErrorBars: false,
    errorBarType: 'std_error',
    enableHatchPatterns: false,
    axisScaleType: 'linear',
    axisTickDirection: 'outside',
    showAxisBaseline: true,
    customAxisTitleX: '',
    customAxisTitleY: '',
    // Axis Titles Customization
    showAxisTitleX: true,
    showAxisTitleY: true,
    axisTitleFontSizeX: 11,
    axisTitleFontSizeY: 11,
    axisTitleFontWeightX: 'bold',
    axisTitleFontWeightY: 'bold',
    axisTitleFontStyleX: 'normal',
    axisTitleFontStyleY: 'normal',
    axisTitleColorX: '',
    axisTitleColorY: '',
    axisTitleLocationX: 'middle',
    axisTitleLocationY: 'middle',
    axisTitleGapX: 28,
    axisTitleGapY: 38,
    axisTitleRotateX: 0,
    axisTitleRotateY: 90,
    axisTitleAlignX: 'center',
    axisTitleAlignY: 'center',
    axisTitleOffsetX_X: 0,
    axisTitleOffsetY_X: 0,
    axisTitleOffsetX_Y: 0,
    axisTitleOffsetY_Y: 0,
    axisTitlePrefixX: '',
    axisTitleSuffixX: '',
    axisTitlePrefixY: '',
    axisTitleSuffixY: '',
    // Axis Tick Labels Customization
    showAxisLabelX: true,
    showAxisLabelY: true,
    axisLabelFontSizeX: 11,
    axisLabelFontSizeY: 11,
    axisLabelFontWeightX: 'normal',
    axisLabelFontWeightY: 'normal',
    axisLabelColorX: '',
    axisLabelColorY: '',
    axisLabelRotateX: 0,
    axisLabelRotateY: 0,
    axisLabelMarginX: 8,
    axisLabelMarginY: 8,
    axisLabelOverflowX: 'none',
    axisLabelOverflowY: 'break',
    axisLabelWidthX: 120,
    axisLabelWidthY: 140,
    axisLabelLineHeightX: 14,
    axisLabelLineHeightY: 14,
    axisLabelFormatX: 'auto',
    axisLabelFormatY: 'auto',
    axisLabelPrefixX: '',
    axisLabelSuffixX: '',
    axisLabelPrefixY: '',
    axisLabelSuffixY: '',
    axisLabelIntervalX: 'auto',
    axisLabelIntervalY: 'auto',
    // Scientific Gridlines
    showGridLinesX: false,
    showGridLinesY: true,
    gridLineStyle: 'dashed',
    gridLineColor: '',
    gridLineOpacity: 100,
    labelFormat: 'ratio_percent',
    barLabelPosition: 'right',
    barLabelFormat: 'ratio_percent',
    barYAxisWidth: 140,
    barYAxisOverflow: 'break',
    barLineHeight: 14,
    barYAxisFontSize: 11,
    barBenchmarkLine: false,
    barBenchmarkValue: 50,
    barBenchmarkLabel: 'Target Benchmark',
    barBenchmarkStyle: 'dashed',
    barBenchmarkColor: '#ef4444',
    legendFormat: 'name',
    barLegendFormat: 'name',
    barLegendPosition: 'top-center',
    legendContextScope: 'global_cohort',
    syncLegendAndBarMetrics: false,
    barLabelContextScope: 'auto',
    legendShowParentPrefix: false,
    legendParentPrefixStyle: 'abbreviated',
    legendGroupByParent: true,
    sunburstLegendLevel: 0,
    sunburstLegendFormat: 'name',
    sunburstLegendPosition: 'bottom-center',
    decimalPrecision: undefined,
    useTildeForCoarse: undefined,
    ratioStyle: undefined,
    forceCohortDenominator: undefined,
    levelCustomGroups: { ...DEFAULT_CUSTOM_GROUPS },
    levelCustomGroupLinks: { ...DEFAULT_CUSTOM_GROUP_LINKS },
    levelTargetFields: { ...DEFAULT_LEVEL_TARGET_FIELDS },
    primaryScopeFilter: '',
    secondaryScopeFilter: '',
    customCategoryMap: {},
    enableManualOverrides: false,
    manualCategoryValues: {},
    customSliceColors: {},
    pieLabelPlacement: 'outside',
    pieRadiusRatio: 64,
    pieLabelWidth: 140,
    pieLeaderLineLength: 12,
    pieLeaderLineLength2: 14,
    pieLabelDistance: 6,
    pieLineHeight: 15,
    barLabelDistance: 5,
    barLabelFontSize: undefined,
    barLabelFontWeight: 'bold',
    barLabelFontStyle: 'normal',
    barLabelColor: '',
    barLabelRotate: 0,
    barLabelShowZero: true,
    barLabelMinThreshold: 0,
    barLabelLineHeight: 14,
    barLabelDecimals: undefined,
    barValueCeiling: 'auto',
    barValueInterval: 'auto',
    // Universal Layout Margins
    gridMarginAuto: true,
    gridMarginTop: 45,
    gridMarginBottom: 45,
    gridMarginLeft: 60,
    gridMarginRight: 45,
    // Universal Data Labels
    universalLabelPosition: 'auto',
    universalLabelDistance: 6,
    universalLabelOverflow: 'break',
    universalMaxLabelWidth: 140,
    universalLabelLineHeight: 14,
    universalLabelFontSize: undefined,
    universalLabelFontWeight: '600',
    universalLabelFontStyle: 'normal',
    universalLabelColor: '',
    universalLabelColorMode: 'auto_contrast',
    universalLabelRotate: 0,
    universalLabelMinThreshold: 0,
    universalLabelShowZero: true,
    // Smart Color Modes
    smartColorMode: 'branch_gradient',
    smartColorPropagation: 'auto_children',
    legendDistance: 20,
    legendWidth: undefined,
    legendLineHeight: 15,
    legendItemGap: 12,
    legendFontSize: undefined,
    legendOverflow: 'break',
    lineWidth: 2.5,
    showLineMarkers: true,
    lineMarkerSize: 8,
    lineAreaOpacity: 15,
    lineStepMode: 'none',
    lineMode: 'cohort_trend',
    lineTimeSteps: 96,
    lineTimeStepIntervalName: 'Time Steps k (15-min intervals / 24-h Cycle)',
    lineYAxisTitle: 'State Uncertainty Tr(P)',
    lineYMin: 0,
    lineYMax: 4.5,
    lineBaselineA: 0.15,
    lineBaselineB: 0.038,
    lineBaselineName: 'Static Architecture (24% CNN / 15% Filter Cohort)',
    lineBaselineColor: '',
    lineBaselineStyle: 'dashed',
    lineEstimatorInitial: 0.15,
    lineEstimatorDrift: 0.11,
    lineEstimatorModulation: 0.05,
    lineEstimatorName: 'Discrete Recursive Estimator (Proposed Gated Pipeline)',
    lineEstimatorColor: '',
    lineEstimatorStyle: 'solid',
    lineThresholdValue: 1.0,
    lineThresholdName: 'Semantic Trigger Threshold (ε)',
    lineThresholdLabel: 'Threshold ε = 1.00',
    lineThresholdColor: '',
    lineThresholdStyle: 'dotted',
    lineThresholdPosition: 'insideEndTop',
    lineThresholdLineWidth: 1.5,
    lineAxisPointerType: 'cross',
    lineMarkerSymbol: 'circle',
    lineXAxisInterval: 'auto',
    lineShowGridLines: true,
    lineGridLeft: 60,
    lineGridRight: 40,
    lineGridTop: 65,
    lineGridBottom: 65,
    lineBaselineAreaOpacity: 0,
    lineEstimatorAreaOpacity: 8,
    lineBaselineFillMode: 'none',
    lineEstimatorFillMode: 'subtle_gradient',
    lineShowTxEvents: true,
    lineTxEventSymbol: 'triangle',
    lineTxEventColor: '',
    lineTxEventSize: 12,
    lineShowTxLabels: true,
    lineTxEventLabel: 'TX',
    lineTxEventSeriesName: 'Physical Radio TX Events',
    roseType: 'none',
    piePadAngle: 2,
    pieCornerRadius: 4,
    pieSort: 'desc',
    pieStartAngle: 90,
    pieMinAngle: 0,
    treemapAlgorithm: 'squarified',
    treemapSquareRatio: 0.5 * (1 + Math.sqrt(5)),
    treemapVisibleDepth: 2,
    treemapGapWidth: 2,
    treemapBorderWidth: 2,
    treemapBorderRadius: 0,
    treemapBorderColorMode: 'auto_bg',
    treemapBorderColor: '',
    treemapNodeClick: 'zoomToNode',
    treemapRoam: false,
    treemapDrillDownIcon: '▶',
    treemapShowBreadcrumb: false,
    treemapBreadcrumbPosition: 'bottom',
    treemapBreadcrumbHeight: 22,
    treemapColorMode: 'branch_gradient',
    treemapCohortMode: 'grouped',
    treemapColorMappingBy: 'index',
    treemapColorAlphaMin: 0.7,
    treemapColorAlphaMax: 1.0,
    treemapColorSaturationMin: 0.6,
    treemapColorSaturationMax: 1.0,
    treemapShowLabels: true,
    treemapLabelPosition: 'inside',
    treemapLabelFormat: 'name_count',
    treemapLabelFontSize: 11,
    treemapLabelFontWeight: '600',
    treemapLabelFontStyle: 'normal',
    treemapLabelColorMode: 'auto_contrast',
    treemapLabelColor: '',
    treemapLabelOverflow: 'break',
    treemapLabelWidth: 120,
    treemapLabelLineHeight: 14,
    treemapShowUpperLabel: false,
    treemapUpperLabelHeight: 24,
    treemapUpperLabelWidth: undefined,
    treemapUpperLabelPosition: 'inside',
    treemapUpperLabelFormat: 'name',
    treemapUpperLabelFontSize: 11,
    treemapUpperLabelFontWeight: 'bold',
    treemapUpperLabelColorMode: 'auto_contrast',
    treemapUpperLabelColor: '',
    treemapUpperLabelBgColor: 'rgba(0,0,0,0.18)',
    treemapVisibleMin: 10,
    treemapChildrenVisibleMin: 0,
    treemapLevelConfigs: { ...DEFAULT_TREEMAP_LEVEL_CONFIGS },
    heatmapCellRadius: 0,
    heatmapColorPreset: 'academic',
    radarShape: 'polygon',
    radarStartAngle: 90,
    radarAreaOpacity: 28,
    radarLineWidth: 2.5,
    radarSplitNumber: 5,
    radarRadius: 65,
    radarCenterX: 50,
    radarCenterY: 52,
    radarAxisLine: true,
    radarAxisLineWidth: 1,
    radarAxisLineType: 'solid',
    radarAxisLineColor: '',
    radarAxisLineOpacity: 100,
    radarSplitLine: true,
    radarSplitLineWidth: 1,
    radarSplitLineType: 'solid',
    radarSplitLineColor: '',
    radarSplitLineOpacity: 100,
    radarSplitArea: true,
    radarSplitAreaTheme: 'stepped',
    radarSplitAreaOpacity: 100,
    radarSplitAreaColor1: '',
    radarSplitAreaColor2: '',
    radarShowAxisScaleLabels: false,
    radarAxisScaleFormat: 'percent',
    radarAxisScaleFontSize: 9,
    radarAxisScaleFontWeight: '500',
    radarAxisScaleColor: '',
    radarScaleMax: 100,
    radarScaleMin: 0,
    radarShowAxisTicks: true,
    radarAxisNameMargin: 15,
    radarAxisNameWidth: 120,
    radarAxisNameOverflow: 'break',
    radarAxisNameLineHeight: 14,
    radarAxisNameFontSize: undefined,
    radarAxisNameFontWeight: 'bold',
    radarAxisNameFontStyle: 'normal',
    radarAxisNameColor: '',
    radarAxisNameBgColor: '',
    radarAxisNamePadding: 0,
    radarAxisNameBorderRadius: 4,
    radarAxisNameBorderColor: '',
    radarAxisNameBorderWidth: 0,
    radarShowDataLabels: false,
    radarDataLabelPosition: 'top',
    radarDataLabelFontSize: 10,
    radarDataLabelFontWeight: 'bold',
    radarDataLabelColor: '',
    radarDataLabelFormat: 'percent',
    radarSmooth: false,
    radarBaselineLineStyle: 'solid',
    radarBaselineSymbol: 'circle',
    radarBaselineSymbolSize: 6,
    radarBaselineAreaColor: '',
    radarBaselineSymbolBorderColor: '',
    radarBaselineSymbolBorderWidth: 0,
    radarMode: 'multi_variable',
    radarVariables: [],
    radarVariableAliases: {},
    radarVariableTargets: {},
    radarIndicatorFormat: 'two_line',
    radarShowTarget: true,
    radarTargetName: 'Horticultural Requirement Target',
    radarTargetValue: 100,
    radarTargetLineStyle: 'dashed',
    radarTargetLineWidth: 2,
    radarTargetColor: '#d9534f',
    radarTargetAreaOpacity: 8,
    radarTargetSmooth: false,
    radarTargetSymbol: 'circle',
    radarTargetSymbolSize: 4,
    radarBaselineName: 'Empirical Cohort Baseline (n={n})',
    radarBaselineColor: '',
    radarTagShareName: 'Tag Share (% of Disclosed Tags, N={N})',
    radarTagShareColor: '#c62828',
    radarTagShareLineStyle: 'dashed',
    radarTagShareLineWidth: 2,
    radarTagShareAreaOpacity: 12,
    radarTagShareSmooth: false,
    radarTagShareSymbol: 'rect',
    radarTagShareSymbolSize: 5,
    funnelAlign: 'center',
    funnelGap: 2,
    funnelNeckWidth: 30,
    funnelNeckHeight: 25,
    funnelLabelPosition: 'inside',
    funnelSort: 'descending',
    funnelLabelFontSize: 11,
    funnelLabelFontWeight: 'bold',
    funnelLabelFontStyle: 'normal',
    funnelLabelColor: '',
    boxplotBoxWidth: 30,
    boxplotShowScatter: false,
    boxplotOrientation: 'vertical',
    boxplotFillColor: '',
    boxplotBorderColor: '',
    scatterPointSize: 10,
    scatterPointOpacity: 80,
    scatterShowRegression: false,
    scatterRegressionType: 'linear',
    bubbleMode: 'categorical_matrix',
    bubbleMinRadius: 12,
    bubbleMaxRadius: 65,
    bubbleOpacity: 85,
    bubbleBorderWidth: 1.5,
    bubbleBorderColor: '#333333',
    bubbleShowLabels: true,
    bubbleLabelFormat: 'count_n',
    bubbleLabelFontSize: 11,
    bubbleLabelColor: '#ffffff',
    bubbleColorMode: 'color_by_x',
    bubbleShowGridLines: true,
    bubbleXAxisName: '',
    bubbleYAxisName: '',
    bubbleXAxisNameGap: 55,
    bubbleYAxisNameGap: 95,
    bubbleXAxisNameLocation: 'middle',
    bubbleYAxisNameLocation: 'middle',
    bubbleAxisTitleFontSize: 12,
    bubbleAxisTitleFontWeight: 'bold',
    bubbleAxisTitleColor: '',
    bubbleGridLeft: 40,
    bubbleGridBottom: 35,
    bubbleGridTop: 45,
    bubbleGridRight: 35,
    bubbleSeriesName: 'Deployments',
    bubbleLegendMode: 'category_series',
    graphRepulsion: 120,
    graphEdgeLength: 90,
    graphGravity: 0.1,
    graphCurveness: 0.2,
    graphShowLinkWeights: true,
    graphNodeSize: 20,
    graphDraggable: true,
    gaugeStartAngle: 225,
    gaugeEndAngle: -45,
    gaugePointerWidth: 6,
    gaugeDialWidth: 14,
    gaugeUnit: 'auto',
    gaugeSplitNumber: 5,
    calendarCellSize: 14,
    calendarYear: 'auto',
    calendarColorPreset: 'academic',
    stackedNormalized: false,
    stackedReverseOrder: false,
    stackedPerBarSorting: 'none',
    stackedShowTotalLabel: false,
    stackedTotalLabelPosition: 'top',
    stackedTotalLabelFormat: '{total}',
    stackedTotalFontSize: 11,
    stackedTotalFontWeight: 'bold',
    stackedTotalColor: '',
    stackedTotalLabelDistance: 4,
    legendType: 'plain',
    legendAlign: 'auto',
    legendIcon: 'inherit',
    legendItemWidth: 25,
    legendItemHeight: 14,
    legendFontWeight: 'normal',
    legendTextColor: '',
    legendBackgroundColor: 'transparent',
    legendBorderColor: 'transparent',
    legendBorderWidth: 0,
    legendBorderRadius: 4,
    legendPadding: 5,
    scatterAxisTitle: 'Boundary Disclosure (%)',
    scatterAxisMin: 0,
    scatterAxisMax: 100,
    scatterAxisInterval: 25,
    scatterSeriesName: 'Boundary Disclosure Rate (%)',
    barSeriesName: 'Cohort Prevalence (%)',
    scatterSymbol: 'diamond',
    scatterSymbolSize: 14,
    scatterColor: '#d9534f',
    scatterBorderColor: '#900',
    scatterBorderWidth: 1.5,
    scatterValues: {},
    scatterAxisNameGap: 24,
    scatterShowDataLabels: false,
    scatterLabelPosition: 'top',
    barColorCustom: '',
    barGridTop: 48,
    barGridBottom: 58,
    barGridLeft: 25,
    barGridRight: 55,
    scatterSortMode: 'prevalence_desc'
  };
}

export const INITIAL_SLOTS_CONFIG: Record<SlotId, SlotConfig> = {
  slot_a: createDefaultSlotConfig('slot_a'),
  slot_b: createDefaultSlotConfig('slot_b'),
  slot_c: createDefaultSlotConfig('slot_c'),
  slot_d: createDefaultSlotConfig('slot_d')
};
