import type { SunburstLevelConfig, SlotConfig, SlotId } from '../types';

export const CUSTOM_GROUPING_KEY = '__custom_grouping__';
export const CUSTOM_GROUPING_LABEL = '✨ [Custom Grouping Layer]';

export const DEFAULT_SUNBURST_LEVEL_CONFIGS: Record<number, SunburstLevelConfig> = {
  0: { r0: 15, r: 40, position: 'inside', rotate: 'tangential', align: 'center', minAngle: 0, borderWidth: 2, fontSize: 12, overflow: 'none', labelFormat: 'name' },
  1: { r0: 40, r: 75, position: 'inside', rotate: 'tangential', align: 'center', minAngle: 0, borderWidth: 1, fontSize: 11, overflow: 'none', labelFormat: 'name' },
  2: { r0: 75, r: 77, position: 'outside', rotate: 'radial', align: 'right', minAngle: 0, borderWidth: 2, fontSize: 10, overflow: 'none', labelFormat: 'name' }
};

export const DEFAULT_CUSTOM_GROUPS: Record<number, string[]> = {};

export const DEFAULT_CUSTOM_GROUP_LINKS: Record<number, Record<string, string>> = {};

export const DEFAULT_LEVEL_TARGET_FIELDS: Record<number, string> = {};

export function createDefaultSlotConfig(slotId: SlotId): SlotConfig {
  const isSlotA = slotId === 'slot_a';
  const isSlotB = slotId === 'slot_b';
  const isSlotC = slotId === 'slot_c';

  return {
    chartType: isSlotA ? 'bar_vertical' : isSlotB ? 'sunburst' : isSlotC ? 'line' : 'pie_donut',
    subTitle: isSlotA ? 'Distribution Overview' : isSlotB ? 'Hierarchical Taxonomy' : isSlotC ? 'Temporal Trend' : 'Proportional Share',
    primaryField: isSlotA ? 'Year' : isSlotB ? CUSTOM_GROUPING_KEY : isSlotC ? 'Year' : 'Import_Source',
    secondaryField: isSlotA ? 'Import_Source' : 'Local_PDF_Status',
    metricMode: 'count',
    sankeyFields: ['Year', 'Import_Source', 'Local_PDF_Status'],
    sankeyLabelPositions: {},
    sankeyMaxNodes: {},
    tailLabelStyle: 'comma_list',
    limitCategories: false,
    maxCategoriesCount: 10,
    numFieldX: 'Overall_QA',
    numFieldY: 'citation_count',
    numFieldSize: 'Year',
    useUmbrellanizer: true,
    splitMultiValues: true,
    excludeEmpty: true,
    showLegend: true,
    legendPosition: 'top',
    showDataLabels: true,
    labelRotation: 0,
    donutRatio: 50,
    smoothLine: true,
    sankeyNodeWidth: 20,
    sankeyNodeGap: 18,
    sankeyLeftPadding: 8,
    sankeyRightPadding: 20,
    sankeyTopPadding: 12,
    sankeyBottomPadding: 8,
    sankeyOrient: 'horizontal',
    sankeyNodeAlign: 'justify',
    sankeyCurveness: 0.5,
    sankeyLinkColorMode: 'gradient',
    sankeyLinkOpacity: 45,
    sankeyNodeBorderRadius: 2,
    sankeyNodeBorderWidth: 1,
    sankeyLayoutIterations: 32,
    sankeyDraggable: true,
    sankeyLabelPosition: 'auto',
    sankeyLabelDistance: 6,
    sankeyLabelOverflow: 'break',
    sankeyMaxLabelWidth: 120,
    sankeyLabelFontSize: undefined,
    sankeyLabelRotate: 0,
    sankeyEmphasisFocus: 'adjacency',
    sankeyLevelLabelFormats: {},
    sankeyLevelNodeGaps: {},
    sankeyLevelLabelDistances: {},
    sankeyLevelNodeWidths: {},
    sankeyLevelPathFilters: {},
    sankeySort: 'desc',
    sankeyLabelLineHeight: 14,
    sankeyLabelFontWeight: '600',
    sankeyLabelColor: '',
    bubbleScale: 1.2,
    gaugeMaxScale: 100,
    sunburstLevelConfigs: { ...DEFAULT_SUNBURST_LEVEL_CONFIGS },
    sunburstSort: 'desc',
    sunburstNodeClick: 'rootToNode',
    sunburstEmphasisFocus: 'ancestor',
    barSorting: 'desc',
    barOrientation: 'horizontal',
    barThickness: 26,
    barBorderRadius: 4,
    barGap: 24,
    barClusterGap: 20,
    barInnerGap: 15,
    enableErrorBars: false,
    errorBarType: 'std_error',
    enableHatchPatterns: false,
    axisScaleType: 'linear',
    axisTickDirection: 'outside',
    showAxisBaseline: true,
    customAxisTitleX: '',
    customAxisTitleY: '',
    // Axis Titles Customization
    showAxisTitleX: true,
    showAxisTitleY: true,
    axisTitleFontSizeX: 11,
    axisTitleFontSizeY: 11,
    axisTitleFontWeightX: 'bold',
    axisTitleFontWeightY: 'bold',
    axisTitleFontStyleX: 'normal',
    axisTitleFontStyleY: 'normal',
    axisTitleColorX: '',
    axisTitleColorY: '',
    axisTitleLocationX: 'middle',
    axisTitleLocationY: 'middle',
    axisTitleGapX: 28,
    axisTitleGapY: 38,
    // Axis Tick Labels Customization
    showAxisLabelX: true,
    showAxisLabelY: true,
    axisLabelFontSizeX: 11,
    axisLabelFontSizeY: 11,
    axisLabelFontWeightX: 'normal',
    axisLabelFontWeightY: 'normal',
    axisLabelColorX: '',
    axisLabelColorY: '',
    axisLabelRotateX: 0,
    axisLabelRotateY: 0,
    axisLabelMarginX: 8,
    axisLabelMarginY: 8,
    axisLabelOverflowX: 'none',
    axisLabelOverflowY: 'none',
    axisLabelWidthX: 120,
    axisLabelWidthY: 140,
    axisLabelLineHeightX: 14,
    axisLabelLineHeightY: 14,
    axisLabelFormatX: 'auto',
    axisLabelFormatY: 'auto',
    axisLabelPrefixX: '',
    axisLabelSuffixX: '',
    axisLabelPrefixY: '',
    axisLabelSuffixY: '',
    axisLabelIntervalX: 'auto',
    axisLabelIntervalY: 'auto',
    // Scientific Gridlines
    showGridLinesX: false,
    showGridLinesY: true,
    gridLineStyle: 'dashed',
    gridLineColor: '',
    gridLineOpacity: 100,
    labelFormat: 'ratio_percent',
    barLabelPosition: 'right',
    barLabelFormat: 'ratio_percent',
    barYAxisWidth: 140,
    barYAxisOverflow: 'break',
    barLineHeight: 14,
    barYAxisFontSize: 11,
    barBenchmarkLine: false,
    barBenchmarkValue: 50,
    barBenchmarkLabel: 'Target Benchmark',
    barBenchmarkStyle: 'dashed',
    barBenchmarkColor: '#ef4444',
    legendFormat: 'name',
    barLegendFormat: 'name',
    barLegendPosition: 'top-center',
    sunburstLegendLevel: 0,
    sunburstLegendFormat: 'name',
    sunburstLegendPosition: 'bottom-center',
    decimalPrecision: undefined,
    useTildeForCoarse: undefined,
    ratioStyle: undefined,
    forceCohortDenominator: undefined,
    levelCustomGroups: { ...DEFAULT_CUSTOM_GROUPS },
    levelCustomGroupLinks: { ...DEFAULT_CUSTOM_GROUP_LINKS },
    levelTargetFields: { ...DEFAULT_LEVEL_TARGET_FIELDS },
    primaryScopeFilter: '',
    secondaryScopeFilter: '',
    customCategoryMap: {},
    enableManualOverrides: false,
    manualCategoryValues: {},
    customSliceColors: {},
    pieLabelPlacement: 'outside',
    pieRadiusRatio: 64,
    pieLabelWidth: 140,
    pieLeaderLineLength: 12,
    pieLeaderLineLength2: 14,
    pieLabelDistance: 6,
    pieLineHeight: 15,
    barLabelDistance: 5,
    barLabelFontSize: undefined,
    barLabelFontWeight: 'bold',
    barLabelFontStyle: 'normal',
    barLabelColor: '',
    barLabelRotate: 0,
    barLabelShowZero: true,
    barLabelMinThreshold: 0,
    barLabelLineHeight: 14,
    barValueCeiling: 'auto',
    barValueInterval: 'auto',
    legendDistance: 20,
    legendWidth: undefined,
    legendLineHeight: 15,
    legendItemGap: 12,
    legendFontSize: undefined,
    legendOverflow: 'break',
    lineWidth: 2.5,
    showLineMarkers: true,
    lineMarkerSize: 8,
    lineAreaOpacity: 15,
    lineStepMode: 'none',
    lineMode: 'cohort_trend',
    lineTimeSteps: 96,
    lineTimeStepIntervalName: 'Time Steps k (15-min intervals / 24-h Cycle)',
    lineYAxisTitle: 'State Uncertainty Tr(P)',
    lineYMin: 0,
    lineYMax: 4.5,
    lineBaselineA: 0.15,
    lineBaselineB: 0.038,
    lineBaselineName: 'Static Architecture (24% CNN / 15% Filter Cohort)',
    lineBaselineColor: '',
    lineBaselineStyle: 'dashed',
    lineEstimatorInitial: 0.15,
    lineEstimatorDrift: 0.11,
    lineEstimatorModulation: 0.05,
    lineEstimatorName: 'Discrete Recursive Estimator (Proposed Gated Pipeline)',
    lineEstimatorColor: '',
    lineEstimatorStyle: 'solid',
    lineThresholdValue: 1.0,
    lineThresholdName: 'Semantic Trigger Threshold (ε)',
    lineThresholdLabel: 'Threshold ε = 1.00',
    lineThresholdColor: '',
    lineThresholdStyle: 'dotted',
    lineThresholdPosition: 'insideEndTop',
    lineThresholdLineWidth: 1.5,
    lineAxisPointerType: 'cross',
    lineMarkerSymbol: 'circle',
    lineXAxisInterval: 'auto',
    lineShowGridLines: true,
    lineGridLeft: 60,
    lineGridRight: 40,
    lineGridTop: 65,
    lineGridBottom: 65,
    lineBaselineAreaOpacity: 0,
    lineEstimatorAreaOpacity: 8,
    lineBaselineFillMode: 'none',
    lineEstimatorFillMode: 'subtle_gradient',
    lineShowTxEvents: true,
    lineTxEventSymbol: 'triangle',
    lineTxEventColor: '',
    lineTxEventSize: 12,
    lineShowTxLabels: true,
    lineTxEventLabel: 'TX',
    lineTxEventSeriesName: 'Physical Radio TX Events',
    roseType: 'none',
    piePadAngle: 2,
    pieCornerRadius: 4,
    treemapAlgorithm: 'squarified',
    treemapVisibleDepth: 2,
    treemapGapWidth: 2,
    treemapBorderWidth: 2,
    heatmapCellRadius: 0,
    heatmapColorPreset: 'academic',
    radarShape: 'polygon',
    radarAreaOpacity: 28,
    radarLineWidth: 2.5,
    radarSplitNumber: 5,
    radarRadius: 65,
    radarAxisLine: true,
    radarSplitLine: true,
    radarSplitArea: true,
    radarAxisNameMargin: 15,
    radarAxisNameWidth: 120,
    radarAxisNameOverflow: 'break',
    radarAxisNameLineHeight: 14,
    radarShowDataLabels: false,
    radarDataLabelPosition: 'top',
    radarBaselineLineStyle: 'solid',
    radarBaselineSymbol: 'circle',
    radarBaselineSymbolSize: 6,
    radarMode: 'multi_variable',
    radarVariables: [],
    radarVariableAliases: {},
    radarVariableTargets: {},
    radarIndicatorFormat: 'two_line',
    radarShowTarget: true,
    radarTargetName: 'Horticultural Requirement Target',
    radarTargetValue: 100,
    radarTargetLineStyle: 'dashed',
    radarTargetLineWidth: 2,
    radarTargetColor: '#d9534f',
    radarTargetAreaOpacity: 8,
    radarTargetSymbol: 'circle',
    radarTargetSymbolSize: 4,
    radarBaselineName: 'Empirical Cohort Baseline (n={n})',
    radarBaselineColor: '',
    funnelAlign: 'center',
    funnelGap: 2,
    funnelNeckWidth: 30,
    funnelNeckHeight: 25,
    boxplotBoxWidth: 30,
    boxplotShowScatter: false,
    boxplotOrientation: 'vertical',
    scatterPointSize: 10,
    scatterPointOpacity: 80,
    scatterShowRegression: false,
    scatterRegressionType: 'linear',
    bubbleMode: 'categorical_matrix',
    bubbleMinRadius: 12,
    bubbleMaxRadius: 65,
    bubbleOpacity: 85,
    bubbleBorderWidth: 1.5,
    bubbleBorderColor: '#333333',
    bubbleShowLabels: true,
    bubbleLabelFormat: 'count_n',
    bubbleLabelFontSize: 11,
    bubbleLabelColor: '#ffffff',
    bubbleColorMode: 'color_by_x',
    bubbleShowGridLines: true,
    bubbleXAxisName: '',
    bubbleYAxisName: '',
    bubbleXAxisNameGap: 55,
    bubbleYAxisNameGap: 95,
    bubbleXAxisNameLocation: 'middle',
    bubbleYAxisNameLocation: 'middle',
    bubbleAxisTitleFontSize: 12,
    bubbleAxisTitleFontWeight: 'bold',
    bubbleAxisTitleColor: '',
    bubbleGridLeft: 40,
    bubbleGridBottom: 35,
    bubbleGridTop: 45,
    bubbleGridRight: 35,
    bubbleSeriesName: 'Deployments',
    bubbleLegendMode: 'category_series',
    graphRepulsion: 120,
    graphEdgeLength: 90,
    graphGravity: 0.1,
    graphCurveness: 0.2,
    graphShowLinkWeights: true,
    gaugeStartAngle: 225,
    gaugeEndAngle: -45,
    gaugePointerWidth: 6,
    gaugeDialWidth: 14,
    calendarCellSize: 14,
    calendarYear: 'auto',
    stackedNormalized: false,
    legendType: 'plain',
    legendAlign: 'auto',
    legendIcon: 'inherit',
    legendItemWidth: 25,
    legendItemHeight: 14,
    legendFontWeight: 'normal',
    legendTextColor: '',
    legendBackgroundColor: 'transparent',
    legendBorderColor: 'transparent',
    legendBorderWidth: 0,
    legendBorderRadius: 4,
    legendPadding: 5,
    scatterAxisTitle: 'Boundary Disclosure (%)',
    scatterAxisMin: 0,
    scatterAxisMax: 100,
    scatterAxisInterval: 25,
    scatterSeriesName: 'Boundary Disclosure Rate (%)',
    barSeriesName: 'Cohort Prevalence (%)',
    scatterSymbol: 'diamond',
    scatterSymbolSize: 14,
    scatterColor: '#d9534f',
    scatterBorderColor: '#900',
    scatterBorderWidth: 1.5,
    scatterValues: {},
    scatterAxisNameGap: 24,
    scatterShowDataLabels: false,
    scatterLabelPosition: 'top',
    barColorCustom: '',
    barGridTop: 48,
    barGridBottom: 58,
    barGridLeft: 4,
    barGridRight: 4,
    scatterSortMode: 'prevalence_desc'
  };
}

export const INITIAL_SLOTS_CONFIG: Record<SlotId, SlotConfig> = {
  slot_a: createDefaultSlotConfig('slot_a'),
  slot_b: createDefaultSlotConfig('slot_b'),
  slot_c: createDefaultSlotConfig('slot_c'),
  slot_d: createDefaultSlotConfig('slot_d')
};
