import React, { useCallback, useMemo } from 'react';
import { useVisualizerLayout } from '../hooks/useVisualizerLayout';
import { useVisualizerConfig } from '../hooks/useVisualizerConfig';
import { useVisualizerData } from '../hooks/useVisualizerData';
import { useVisualizerStyle } from '../hooks/useVisualizerStyle';
import { useVisualizerCamera } from '../hooks/useVisualizerCamera';
import { useVisualizerWorkspace } from '../hooks/useVisualizerWorkspace';
import { useVisualizerPresets } from '../hooks/useVisualizerPresets';
import { useChartCanvas } from '../hooks/useChartCanvas';
import { buildChartOption } from '../generators';
import { VisualizerContext, type VisualizerContextValue } from './VisualizerContext';
import type { VisualizerModalProps, SlotId } from '../types';

interface VisualizerProviderProps {
  children: React.ReactNode;
  props: VisualizerModalProps;
}

export function VisualizerProvider({ children, props }: VisualizerProviderProps) {
  const { papers, isOpen, umbrellanizerMap = {} } = props;

  const layout = useVisualizerLayout();

  const config = useVisualizerConfig({
    activeSlot: layout.activeSlot
  });

  const data = useVisualizerData({
    papers,
    activeSlot: layout.activeSlot,
    currentSlotConfig: config.currentSlotConfig,
    updateActiveSlot: config.updateActiveSlot,
    umbrellanizerMap
  });

  const style = useVisualizerStyle();
  const camera = useVisualizerCamera();

  const workspace = useVisualizerWorkspace({
    isOpen,
    currentStep: config.currentStep,
    setCurrentStep: config.setCurrentStep,
    onClose: props.onClose
  });

  const presets = useVisualizerPresets({
    layout,
    config,
    style,
    camera
  });

  const generateSlotOption = useCallback((slotId: SlotId, overrides?: any) => {
    const slotConfig = config.slotsConfig[slotId] || config.currentSlotConfig;
    const isSingle = layout.layoutMode === 'single';

    return buildChartOption({
      chartType: slotConfig.chartType,
      papers,
      themePreset: style.themePreset,
      fontFamily: style.fontFamily,
      fontSize: style.fontSize,
      chartTitle: '',
      chartSubtitle: '',
      showChartTitle: false,
      showChartSubtitle: false,
      showLegend: slotConfig.showLegend,
      legendPosition: slotConfig.legendPosition,
      showDataLabels: slotConfig.showDataLabels,
      labelRotation: slotConfig.labelRotation,
      primaryField: slotConfig.primaryField,
      secondaryField: slotConfig.secondaryField,
      metricMode: slotConfig.metricMode,
      sankeyFields: slotConfig.sankeyFields,
      sankeyLabelPositions: slotConfig.sankeyLabelPositions,
      sankeyMaxNodes: slotConfig.sankeyMaxNodes,
      tailLabelStyle: slotConfig.tailLabelStyle,
      limitCategories: slotConfig.limitCategories,
      maxCategoriesCount: slotConfig.maxCategoriesCount,
      numFieldX: slotConfig.numFieldX,
      numFieldY: slotConfig.numFieldY,
      numFieldSize: slotConfig.numFieldSize,
      useUmbrellanizer: slotConfig.useUmbrellanizer,
      splitMultiValues: slotConfig.splitMultiValues,
      excludeEmpty: slotConfig.excludeEmpty,
      donutRatio: slotConfig.donutRatio,
      smoothLine: slotConfig.smoothLine,
      sankeyNodeWidth: slotConfig.sankeyNodeWidth,
      sankeyNodeGap: slotConfig.sankeyNodeGap,
      sankeyLeftPadding: slotConfig.sankeyLeftPadding,
      sankeyRightPadding: slotConfig.sankeyRightPadding,
      sankeyTopPadding: slotConfig.sankeyTopPadding,
      sankeyBottomPadding: slotConfig.sankeyBottomPadding,
      sankeyOrient: slotConfig.sankeyOrient,
      sankeyNodeAlign: slotConfig.sankeyNodeAlign,
      sankeyCurveness: slotConfig.sankeyCurveness,
      sankeyLinkColorMode: slotConfig.sankeyLinkColorMode,
      sankeyLinkOpacity: slotConfig.sankeyLinkOpacity,
      sankeyNodeBorderRadius: slotConfig.sankeyNodeBorderRadius,
      sankeyNodeBorderWidth: slotConfig.sankeyNodeBorderWidth,
      sankeyLayoutIterations: slotConfig.sankeyLayoutIterations,
      sankeyDraggable: slotConfig.sankeyDraggable,
      sankeyLabelPosition: slotConfig.sankeyLabelPosition,
      sankeyLabelDistance: slotConfig.sankeyLabelDistance,
      sankeyLabelOverflow: slotConfig.sankeyLabelOverflow,
      sankeyMaxLabelWidth: slotConfig.sankeyMaxLabelWidth,
      sankeyLabelFontSize: slotConfig.sankeyLabelFontSize,
      sankeyLabelRotate: slotConfig.sankeyLabelRotate,
      sankeyEmphasisFocus: slotConfig.sankeyEmphasisFocus,
      sankeyLevelLabelFormats: slotConfig.sankeyLevelLabelFormats,
      sankeyLevelNodeGaps: slotConfig.sankeyLevelNodeGaps,
      sankeyLevelLabelDistances: slotConfig.sankeyLevelLabelDistances,
      sankeyLevelNodeWidths: slotConfig.sankeyLevelNodeWidths,
      sankeyLevelPathFilters: slotConfig.sankeyLevelPathFilters,
      sankeySort: slotConfig.sankeySort,
      sankeyLabelLineHeight: slotConfig.sankeyLabelLineHeight,
      sankeyLabelFontWeight: slotConfig.sankeyLabelFontWeight,
      sankeyLabelColor: slotConfig.sankeyLabelColor,
      bubbleScale: slotConfig.bubbleScale,
      gaugeMaxScale: slotConfig.gaugeMaxScale,
      sunburstLevelConfigs: slotConfig.sunburstLevelConfigs,
      sunburstSort: slotConfig.sunburstSort,
      sunburstNodeClick: slotConfig.sunburstNodeClick,
      sunburstEmphasisFocus: slotConfig.sunburstEmphasisFocus,
      barSorting: slotConfig.barSorting,
      barOrientation: slotConfig.barOrientation || 'horizontal',
      barThickness: slotConfig.barThickness,
      barBorderRadius: slotConfig.barBorderRadius,
      barGap: slotConfig.barGap,
      barClusterGap: slotConfig.barClusterGap ?? 20,
      barInnerGap: slotConfig.barInnerGap ?? 15,
      enableErrorBars: slotConfig.enableErrorBars ?? false,
      errorBarType: slotConfig.errorBarType || 'std_error',
      enableHatchPatterns: slotConfig.enableHatchPatterns ?? false,
      axisScaleType: slotConfig.axisScaleType || 'linear',
      axisTickDirection: slotConfig.axisTickDirection || 'outside',
      showAxisBaseline: slotConfig.showAxisBaseline ?? true,
      customAxisTitleX: slotConfig.customAxisTitleX || '',
      customAxisTitleY: slotConfig.customAxisTitleY || '',
      showAxisTitleX: slotConfig.showAxisTitleX ?? true,
      showAxisTitleY: slotConfig.showAxisTitleY ?? true,
      axisTitleFontSizeX: slotConfig.axisTitleFontSizeX ?? 11,
      axisTitleFontSizeY: slotConfig.axisTitleFontSizeY ?? 11,
      axisTitleFontWeightX: slotConfig.axisTitleFontWeightX || 'bold',
      axisTitleFontWeightY: slotConfig.axisTitleFontWeightY || 'bold',
      axisTitleFontStyleX: slotConfig.axisTitleFontStyleX || 'normal',
      axisTitleFontStyleY: slotConfig.axisTitleFontStyleY || 'normal',
      axisTitleColorX: slotConfig.axisTitleColorX || '',
      axisTitleColorY: slotConfig.axisTitleColorY || '',
      axisTitleLocationX: slotConfig.axisTitleLocationX || 'middle',
      axisTitleLocationY: slotConfig.axisTitleLocationY || 'middle',
      axisTitleGapX: slotConfig.axisTitleGapX ?? 28,
      axisTitleGapY: slotConfig.axisTitleGapY ?? 38,
      showAxisLabelX: slotConfig.showAxisLabelX ?? true,
      showAxisLabelY: slotConfig.showAxisLabelY ?? true,
      axisLabelFontSizeX: slotConfig.axisLabelFontSizeX ?? 11,
      axisLabelFontSizeY: slotConfig.axisLabelFontSizeY ?? 11,
      axisLabelFontWeightX: slotConfig.axisLabelFontWeightX || 'normal',
      axisLabelFontWeightY: slotConfig.axisLabelFontWeightY || 'normal',
      axisLabelColorX: slotConfig.axisLabelColorX || '',
      axisLabelColorY: slotConfig.axisLabelColorY || '',
      axisLabelRotateX: slotConfig.axisLabelRotateX ?? 0,
      axisLabelRotateY: slotConfig.axisLabelRotateY ?? 0,
      axisLabelMarginX: slotConfig.axisLabelMarginX ?? 8,
      axisLabelMarginY: slotConfig.axisLabelMarginY ?? 8,
      axisLabelOverflowX: slotConfig.axisLabelOverflowX || 'none',
      axisLabelOverflowY: slotConfig.axisLabelOverflowY || 'none',
      axisLabelWidthX: slotConfig.axisLabelWidthX ?? 120,
      axisLabelWidthY: slotConfig.axisLabelWidthY ?? 140,
      axisLabelLineHeightX: slotConfig.axisLabelLineHeightX ?? 14,
      axisLabelLineHeightY: slotConfig.axisLabelLineHeightY ?? 14,
      axisLabelFormatX: slotConfig.axisLabelFormatX || 'auto',
      axisLabelFormatY: slotConfig.axisLabelFormatY || 'auto',
      axisLabelPrefixX: slotConfig.axisLabelPrefixX || '',
      axisLabelSuffixX: slotConfig.axisLabelSuffixX || '',
      axisLabelPrefixY: slotConfig.axisLabelPrefixY || '',
      axisLabelSuffixY: slotConfig.axisLabelSuffixY || '',
      axisLabelIntervalX: slotConfig.axisLabelIntervalX ?? 'auto',
      axisLabelIntervalY: slotConfig.axisLabelIntervalY ?? 'auto',
      showGridLinesX: slotConfig.showGridLinesX ?? false,
      showGridLinesY: slotConfig.showGridLinesY ?? true,
      gridLineStyle: slotConfig.gridLineStyle || 'dashed',
      gridLineColor: slotConfig.gridLineColor || '',
      gridLineOpacity: slotConfig.gridLineOpacity ?? 100,
      labelFormat: slotConfig.labelFormat || style.defaultLabelFormat || 'ratio_percent',
      barLabelPosition: slotConfig.barLabelPosition,
      barLabelFormat: slotConfig.barLabelFormat || style.defaultLabelFormat || 'ratio_percent',
      barYAxisWidth: slotConfig.barYAxisWidth,
      barYAxisOverflow: slotConfig.barYAxisOverflow,
      barLineHeight: slotConfig.barLineHeight ?? 14,
      barYAxisFontSize: slotConfig.barYAxisFontSize ?? 11,
      barBenchmarkLine: slotConfig.barBenchmarkLine,
      barBenchmarkValue: slotConfig.barBenchmarkValue,
      barBenchmarkLabel: slotConfig.barBenchmarkLabel,
      barBenchmarkStyle: slotConfig.barBenchmarkStyle,
      barBenchmarkColor: slotConfig.barBenchmarkColor,
      legendFormat: slotConfig.legendFormat || style.defaultLegendFormat || 'name',
      barLegendFormat: slotConfig.barLegendFormat || style.defaultLegendFormat || 'name',
      barLegendPosition: slotConfig.barLegendPosition,
      decimalPrecision: style.decimalPrecision,
      useTildeForCoarse: style.useTildeForCoarse,
      ratioStyle: style.ratioStyle,
      forceCohortDenominator: style.forceCohortDenominator,
      chartScale: camera.chartScale,
      panX: camera.panX,
      panY: camera.panY,
      tiltAngle: camera.tiltAngle,
      rotationAngle: camera.rotationAngle,
      fitOffsetX: camera.fitOffsetX,
      fitOffsetY: camera.fitOffsetY,
      containerPadding: camera.containerPadding,
      sunburstLegendLevel: slotConfig.sunburstLegendLevel,
      sunburstLegendFormat: slotConfig.sunburstLegendFormat || style.defaultLegendFormat || 'name',
      sunburstLegendPosition: slotConfig.sunburstLegendPosition,
      levelCustomGroups: slotConfig.levelCustomGroups,
      levelCustomGroupLinks: slotConfig.levelCustomGroupLinks,
      levelTargetFields: slotConfig.levelTargetFields,
      customCategoryMap: slotConfig.customCategoryMap,
      enableManualOverrides: slotConfig.enableManualOverrides,
      manualCategoryValues: slotConfig.manualCategoryValues,
      customSliceColors: slotConfig.customSliceColors,
      pieLabelPlacement: slotConfig.pieLabelPlacement,
      pieRadiusRatio: slotConfig.pieRadiusRatio,
      pieLabelWidth: slotConfig.pieLabelWidth,
      pieLeaderLineLength: slotConfig.pieLeaderLineLength,
      pieLeaderLineLength2: slotConfig.pieLeaderLineLength2,
      pieLabelDistance: slotConfig.pieLabelDistance,
      pieLineHeight: slotConfig.pieLineHeight,
      barLabelDistance: slotConfig.barLabelDistance,
      barLabelFontSize: slotConfig.barLabelFontSize,
      barLabelFontWeight: slotConfig.barLabelFontWeight,
      barLabelFontStyle: slotConfig.barLabelFontStyle,
      barLabelColor: slotConfig.barLabelColor,
      barLabelRotate: slotConfig.barLabelRotate,
      barLabelShowZero: slotConfig.barLabelShowZero,
      barLabelMinThreshold: slotConfig.barLabelMinThreshold,
      barLabelLineHeight: slotConfig.barLabelLineHeight,
      barValueCeiling: slotConfig.barValueCeiling,
      barValueInterval: slotConfig.barValueInterval,
      legendDistance: slotConfig.legendDistance,
      legendWidth: slotConfig.legendWidth,
      legendLineHeight: slotConfig.legendLineHeight,
      legendItemGap: slotConfig.legendItemGap,
      legendFontSize: slotConfig.legendFontSize,
      legendOverflow: slotConfig.legendOverflow,
      umbrellanizerMap,
      lineMode: slotConfig.lineMode,
      lineTimeSteps: slotConfig.lineTimeSteps,
      lineTimeStepIntervalName: slotConfig.lineTimeStepIntervalName,
      lineYAxisTitle: slotConfig.lineYAxisTitle,
      lineYMin: slotConfig.lineYMin,
      lineYMax: slotConfig.lineYMax,
      lineBaselineA: slotConfig.lineBaselineA,
      lineBaselineB: slotConfig.lineBaselineB,
      lineBaselineName: slotConfig.lineBaselineName,
      lineBaselineColor: slotConfig.lineBaselineColor,
      lineBaselineStyle: slotConfig.lineBaselineStyle,
      lineEstimatorInitial: slotConfig.lineEstimatorInitial,
      lineEstimatorDrift: slotConfig.lineEstimatorDrift,
      lineEstimatorModulation: slotConfig.lineEstimatorModulation,
      lineEstimatorName: slotConfig.lineEstimatorName,
      lineEstimatorColor: slotConfig.lineEstimatorColor,
      lineEstimatorStyle: slotConfig.lineEstimatorStyle,
      lineThresholdValue: slotConfig.lineThresholdValue,
      lineThresholdName: slotConfig.lineThresholdName,
      lineThresholdLabel: slotConfig.lineThresholdLabel,
      lineThresholdColor: slotConfig.lineThresholdColor,
      lineThresholdStyle: slotConfig.lineThresholdStyle,
      lineThresholdPosition: slotConfig.lineThresholdPosition,
      lineThresholdLineWidth: slotConfig.lineThresholdLineWidth,
      lineAxisPointerType: slotConfig.lineAxisPointerType,
      lineMarkerSymbol: slotConfig.lineMarkerSymbol,
      lineXAxisInterval: slotConfig.lineXAxisInterval,
      lineShowGridLines: slotConfig.lineShowGridLines,
      lineGridLeft: slotConfig.lineGridLeft,
      lineGridRight: slotConfig.lineGridRight,
      lineGridTop: slotConfig.lineGridTop,
      lineGridBottom: slotConfig.lineGridBottom,
      lineWidth: slotConfig.lineWidth,
      showLineMarkers: slotConfig.showLineMarkers,
      lineMarkerSize: slotConfig.lineMarkerSize,
      lineAreaOpacity: slotConfig.lineAreaOpacity,
      lineBaselineAreaOpacity: slotConfig.lineBaselineAreaOpacity,
      lineEstimatorAreaOpacity: slotConfig.lineEstimatorAreaOpacity,
      lineBaselineFillMode: slotConfig.lineBaselineFillMode,
      lineEstimatorFillMode: slotConfig.lineEstimatorFillMode,
      lineShowTxEvents: slotConfig.lineShowTxEvents,
      lineTxEventSymbol: slotConfig.lineTxEventSymbol,
      lineTxEventColor: slotConfig.lineTxEventColor,
      lineTxEventSize: slotConfig.lineTxEventSize,
      lineShowTxLabels: slotConfig.lineShowTxLabels,
      lineTxEventLabel: slotConfig.lineTxEventLabel,
      lineTxEventSeriesName: slotConfig.lineTxEventSeriesName,
      lineStepMode: slotConfig.lineStepMode,
      roseType: slotConfig.roseType,
      piePadAngle: slotConfig.piePadAngle,
      pieCornerRadius: slotConfig.pieCornerRadius,
      treemapAlgorithm: slotConfig.treemapAlgorithm,
      treemapVisibleDepth: slotConfig.treemapVisibleDepth,
      treemapGapWidth: slotConfig.treemapGapWidth,
      treemapBorderWidth: slotConfig.treemapBorderWidth,
      heatmapCellRadius: slotConfig.heatmapCellRadius,
      heatmapColorPreset: slotConfig.heatmapColorPreset,
      radarShape: slotConfig.radarShape,
      radarAreaOpacity: slotConfig.radarAreaOpacity,
      radarLineWidth: slotConfig.radarLineWidth,
      radarSplitNumber: slotConfig.radarSplitNumber,
      radarRadius: slotConfig.radarRadius,
      radarAxisLine: slotConfig.radarAxisLine,
      radarSplitLine: slotConfig.radarSplitLine,
      radarSplitArea: slotConfig.radarSplitArea,
      radarAxisNameMargin: slotConfig.radarAxisNameMargin,
      radarAxisNameWidth: slotConfig.radarAxisNameWidth,
      radarAxisNameOverflow: slotConfig.radarAxisNameOverflow,
      radarAxisNameLineHeight: slotConfig.radarAxisNameLineHeight,
      radarShowDataLabels: slotConfig.radarShowDataLabels,
      radarDataLabelPosition: slotConfig.radarDataLabelPosition,
      radarBaselineLineStyle: slotConfig.radarBaselineLineStyle,
      radarBaselineSymbol: slotConfig.radarBaselineSymbol,
      radarBaselineSymbolSize: slotConfig.radarBaselineSymbolSize,
      radarMode: slotConfig.radarMode,
      radarVariables: slotConfig.radarVariables,
      radarVariableAliases: slotConfig.radarVariableAliases,
      radarVariableTargets: slotConfig.radarVariableTargets,
      radarIndicatorFormat: slotConfig.radarIndicatorFormat,
      radarShowTarget: slotConfig.radarShowTarget,
      radarTargetName: slotConfig.radarTargetName,
      radarTargetValue: slotConfig.radarTargetValue,
      radarTargetLineStyle: slotConfig.radarTargetLineStyle,
      radarTargetLineWidth: slotConfig.radarTargetLineWidth,
      radarTargetColor: slotConfig.radarTargetColor,
      radarTargetAreaOpacity: slotConfig.radarTargetAreaOpacity,
      radarTargetSymbol: slotConfig.radarTargetSymbol,
      radarTargetSymbolSize: slotConfig.radarTargetSymbolSize,
      radarBaselineName: slotConfig.radarBaselineName,
      radarBaselineColor: slotConfig.radarBaselineColor,
      funnelAlign: slotConfig.funnelAlign,
      funnelGap: slotConfig.funnelGap,
      funnelNeckWidth: slotConfig.funnelNeckWidth,
      funnelNeckHeight: slotConfig.funnelNeckHeight,
      boxplotBoxWidth: slotConfig.boxplotBoxWidth,
      boxplotShowScatter: slotConfig.boxplotShowScatter,
      boxplotOrientation: slotConfig.boxplotOrientation,
      scatterPointSize: slotConfig.scatterPointSize,
      scatterPointOpacity: slotConfig.scatterPointOpacity,
      scatterShowRegression: slotConfig.scatterShowRegression,
      scatterRegressionType: slotConfig.scatterRegressionType,
      bubbleMode: slotConfig.bubbleMode,
      bubbleMinRadius: slotConfig.bubbleMinRadius,
      bubbleMaxRadius: slotConfig.bubbleMaxRadius,
      bubbleOpacity: slotConfig.bubbleOpacity,
      bubbleBorderWidth: slotConfig.bubbleBorderWidth,
      bubbleBorderColor: slotConfig.bubbleBorderColor,
      bubbleShowLabels: slotConfig.bubbleShowLabels,
      bubbleLabelFormat: slotConfig.bubbleLabelFormat,
      bubbleLabelFontSize: slotConfig.bubbleLabelFontSize,
      bubbleLabelColor: slotConfig.bubbleLabelColor,
      bubbleColorMode: slotConfig.bubbleColorMode,
      bubbleShowGridLines: slotConfig.bubbleShowGridLines,
      bubbleComplianceRules: slotConfig.bubbleComplianceRules,
      bubbleXAxisName: slotConfig.bubbleXAxisName,
      bubbleYAxisName: slotConfig.bubbleYAxisName,
      bubbleXAxisNameGap: slotConfig.bubbleXAxisNameGap,
      bubbleYAxisNameGap: slotConfig.bubbleYAxisNameGap,
      bubbleXAxisNameLocation: slotConfig.bubbleXAxisNameLocation,
      bubbleYAxisNameLocation: slotConfig.bubbleYAxisNameLocation,
      bubbleAxisTitleFontSize: slotConfig.bubbleAxisTitleFontSize,
      bubbleAxisTitleFontWeight: slotConfig.bubbleAxisTitleFontWeight,
      bubbleAxisTitleColor: slotConfig.bubbleAxisTitleColor,
      bubbleGridLeft: slotConfig.bubbleGridLeft,
      bubbleGridBottom: slotConfig.bubbleGridBottom,
      bubbleGridTop: slotConfig.bubbleGridTop,
      bubbleGridRight: slotConfig.bubbleGridRight,
      bubbleSeriesName: slotConfig.bubbleSeriesName,
      bubbleLegendMode: slotConfig.bubbleLegendMode,
      graphRepulsion: slotConfig.graphRepulsion,
      graphEdgeLength: slotConfig.graphEdgeLength,
      graphGravity: slotConfig.graphGravity,
      graphCurveness: slotConfig.graphCurveness,
      graphShowLinkWeights: slotConfig.graphShowLinkWeights,
      gaugeStartAngle: slotConfig.gaugeStartAngle,
      gaugeEndAngle: slotConfig.gaugeEndAngle,
      gaugePointerWidth: slotConfig.gaugePointerWidth,
      gaugeDialWidth: slotConfig.gaugeDialWidth,
      calendarCellSize: slotConfig.calendarCellSize,
      calendarYear: slotConfig.calendarYear,
      stackedNormalized: slotConfig.stackedNormalized,
      legendType: slotConfig.legendType,
      legendAlign: slotConfig.legendAlign,
      legendIcon: slotConfig.legendIcon,
      legendItemWidth: slotConfig.legendItemWidth,
      legendItemHeight: slotConfig.legendItemHeight,
      legendFontWeight: slotConfig.legendFontWeight,
      legendTextColor: slotConfig.legendTextColor,
      legendBackgroundColor: slotConfig.legendBackgroundColor,
      legendBorderColor: slotConfig.legendBorderColor,
      legendBorderWidth: slotConfig.legendBorderWidth,
      legendBorderRadius: slotConfig.legendBorderRadius,
      legendPadding: slotConfig.legendPadding,
      ...overrides
    });
  }, [config.slotsConfig, config.currentSlotConfig, layout.layoutMode, papers, style, camera, umbrellanizerMap]);

  const canvas = useChartCanvas({
    isOpen,
    currentStep: config.currentStep,
    layoutMode: layout.layoutMode,
    activeSlotsList: layout.activeSlotsList,
    activeSlot: layout.activeSlot,
    themePreset: style.themePreset,
    fontFamily: style.fontFamily,
    fontSize: style.fontSize,
    chartTitle: style.chartTitle,
    chartSubtitle: style.chartSubtitle,
    showChartTitle: style.showChartTitle,
    showChartSubtitle: style.showChartSubtitle,
    subfigureLabelStyle: style.subfigureLabelStyle,
    panelGutter: style.panelGutter,
    showPanelBorders: style.showPanelBorders,
    aspectRatio: style.aspectRatio,
    customWidth: style.customWidth,
    customHeight: style.customHeight,
    dimensionUnit: style.dimensionUnit,
    slotsConfig: config.slotsConfig,
    chartScale: camera.chartScale,
    panX: camera.panX,
    panY: camera.panY,
    tiltAngle: camera.tiltAngle,
    rotationAngle: camera.rotationAngle,
    fitOffsetX: camera.fitOffsetX,
    fitOffsetY: camera.fitOffsetY,
    containerPadding: camera.containerPadding,
    inspectedSlot: workspace.inspectedSlot,
    generateSlotOption
  });

  const value: VisualizerContextValue = useMemo(() => ({
    props,
    layout,
    config,
    data,
    style,
    camera,
    workspace,
    presets,
    canvas,
    generateSlotOption
  }), [props, layout, config, data, style, camera, workspace, presets, canvas, generateSlotOption]);

  return (
    <VisualizerContext.Provider value={value}>
      {children}
    </VisualizerContext.Provider>
  );
}
