import React, { useCallback, useMemo, useState, useEffect, useRef } from 'react';
import { useVisualizerLayout } from '../hooks/useVisualizerLayout';
import { useVisualizerConfig } from '../hooks/useVisualizerConfig';
import { useVisualizerData } from '../hooks/useVisualizerData';
import { useVisualizerStyle } from '../hooks/useVisualizerStyle';
import { useVisualizerCamera } from '../hooks/useVisualizerCamera';
import { useVisualizerWorkspace } from '../hooks/useVisualizerWorkspace';
import { useVisualizerPresets } from '../hooks/useVisualizerPresets';
import { useChartCanvas } from '../hooks/useChartCanvas';
import { buildChartOption } from '../generators';
import { VisualizerContext, type VisualizerContextValue } from './VisualizerContext';
import type { VisualizerModalProps, SlotId } from '../types';
import { subscribeSyncChannel } from '@/lib/sync-utils';

interface VisualizerProviderProps {
  children: React.ReactNode;
  props: VisualizerModalProps;
}

export function VisualizerProvider({ children, props }: VisualizerProviderProps) {
  const {
    papers: propPapers = [],
    allCohortPapers: propAllCohortPapers,
    projectId,
    autoFetchFromDb = true,
    initialCohortScope = 'full',
    isOpen,
    umbrellanizerMap = {},
    isFiltered: propIsFiltered = false
  } = props;

  // Cohort Scope State ('full' by default for authoritative full study cohort N=46)
  const [cohortScope, setCohortScope] = useState<'full' | 'filtered'>(initialCohortScope);
  const [dbCohortPapers, setDbCohortPapers] = useState<any[] | null>(null);
  const [isLoadingDbCohort, setIsLoadingDbCohort] = useState<boolean>(false);

  // Fallback direct DB fetch if allCohortPapers was not provided by the parent
  const fetchDbCohort = useCallback(async () => {
    if (!projectId || typeof window === 'undefined') return;
    try {
      setIsLoadingDbCohort(true);
      const res = await fetch(`/api/insight/final-cohort?projectId=${encodeURIComponent(String(projectId))}&limit=10000`);
      if (res.ok) {
        const json = await res.json();
        if (Array.isArray(json.papers)) {
          setDbCohortPapers(json.papers);
        }
      }
    } catch (err) {
      console.warn('[VisualizerProvider] Autonomous DB cohort fetch bypassed/failed (offline SPA or API error):', err);
    } finally {
      setIsLoadingDbCohort(false);
    }
  }, [projectId]);

  // Trigger DB fetch on modal open if allCohortPapers is absent and autoFetchFromDb is enabled
  useEffect(() => {
    if (isOpen && autoFetchFromDb && (!propAllCohortPapers || propAllCohortPapers.length === 0) && projectId) {
      fetchDbCohort();
    }
  }, [isOpen, autoFetchFromDb, propAllCohortPapers, projectId, fetchDbCohort]);

  // Subscribe to Multi-Tab Sync (SYNC_PAPERS) to keep DB cohort updated
  const fetchDbCohortRef = useRef(fetchDbCohort);
  fetchDbCohortRef.current = fetchDbCohort;

  useEffect(() => {
    if (!isOpen || !projectId) return;
    const unsub = subscribeSyncChannel((type) => {
      if (type === 'SYNC_PAPERS') {
        fetchDbCohortRef.current();
      }
    });
    return () => unsub();
  }, [isOpen, projectId]);

  // Determine effective full cohort papers and active working papers
  const effectiveFullCohort = useMemo(() => {
    if (propAllCohortPapers && propAllCohortPapers.length > 0) {
      return propAllCohortPapers;
    }
    if (dbCohortPapers && dbCohortPapers.length > 0) {
      return dbCohortPapers;
    }
    return propPapers;
  }, [propAllCohortPapers, dbCohortPapers, propPapers]);

  const activePapers = useMemo(() => {
    return cohortScope === 'full' ? effectiveFullCohort : propPapers;
  }, [cohortScope, effectiveFullCohort, propPapers]);

  const fullCohortCount = effectiveFullCohort.length;
  const filteredCohortCount = propPapers.length;
  const isFiltered = propIsFiltered || (filteredCohortCount < fullCohortCount);

  const layout = useVisualizerLayout();

  const config = useVisualizerConfig({
    activeSlot: layout.activeSlot
  });

  const data = useVisualizerData({
    papers: activePapers,
    activeSlot: layout.activeSlot,
    currentSlotConfig: config.currentSlotConfig,
    updateActiveSlot: config.updateActiveSlot,
    umbrellanizerMap
  });

  const style = useVisualizerStyle();
  const camera = useVisualizerCamera();

  const workspace = useVisualizerWorkspace({
    isOpen,
    currentStep: config.currentStep,
    setCurrentStep: config.setCurrentStep,
    onClose: props.onClose,
    cohortScope,
    setCohortScope,
    fullCohortCount,
    filteredCohortCount,
    isFiltered,
    isLoadingDbCohort
  });

  const presets = useVisualizerPresets({
    layout,
    config,
    style,
    camera
  });

  const generateSlotOption = useCallback((slotId: SlotId, overrides?: any) => {
    const slotConfig = config.slotsConfig[slotId] || config.currentSlotConfig;
    const isSingle = layout.layoutMode === 'single';

    return buildChartOption({
      chartType: slotConfig.chartType,
      papers: activePapers,
      themePreset: style.themePreset,
      fontFamily: style.fontFamily,
      fontSize: style.fontSize,
      chartTitle: '',
      chartSubtitle: '',
      showChartTitle: false,
      showChartSubtitle: false,
      showLegend: slotConfig.showLegend,
      legendPosition: slotConfig.legendPosition,
      showDataLabels: slotConfig.showDataLabels,
      labelRotation: slotConfig.labelRotation,
      primaryField: slotConfig.primaryField,
      secondaryField: slotConfig.secondaryField,
      metricMode: slotConfig.metricMode,
      sankeyFields: slotConfig.sankeyFields,
      sankeyLabelPositions: slotConfig.sankeyLabelPositions,
      sankeyMaxNodes: slotConfig.sankeyMaxNodes,
      tailLabelStyle: slotConfig.tailLabelStyle,
      limitCategories: slotConfig.limitCategories,
      maxCategoriesCount: slotConfig.maxCategoriesCount,
      numFieldX: slotConfig.numFieldX,
      numFieldY: slotConfig.numFieldY,
      numFieldSize: slotConfig.numFieldSize,
      useUmbrellanizer: slotConfig.useUmbrellanizer,
      splitMultiValues: slotConfig.splitMultiValues,
      excludeEmpty: slotConfig.excludeEmpty,
      donutRatio: slotConfig.donutRatio,
      smoothLine: slotConfig.smoothLine,
      sankeyNodeWidth: slotConfig.sankeyNodeWidth,
      sankeyNodeGap: slotConfig.sankeyNodeGap,
      sankeyLeftPadding: slotConfig.sankeyLeftPadding,
      sankeyRightPadding: slotConfig.sankeyRightPadding,
      sankeyTopPadding: slotConfig.sankeyTopPadding,
      sankeyBottomPadding: slotConfig.sankeyBottomPadding,
      sankeyOrient: slotConfig.sankeyOrient,
      sankeyNodeAlign: slotConfig.sankeyNodeAlign,
      sankeyCurveness: slotConfig.sankeyCurveness,
      sankeyLinkColorMode: slotConfig.sankeyLinkColorMode,
      sankeyLinkOpacity: slotConfig.sankeyLinkOpacity,
      sankeyNodeBorderRadius: slotConfig.sankeyNodeBorderRadius,
      sankeyNodeBorderWidth: slotConfig.sankeyNodeBorderWidth,
      sankeyLayoutIterations: slotConfig.sankeyLayoutIterations,
      sankeyDraggable: slotConfig.sankeyDraggable,
      sankeyLabelPosition: slotConfig.sankeyLabelPosition,
      sankeyLabelDistance: slotConfig.sankeyLabelDistance,
      sankeyLabelOverflow: slotConfig.sankeyLabelOverflow,
      sankeyMaxLabelWidth: slotConfig.sankeyMaxLabelWidth,
      sankeyLabelFontSize: slotConfig.sankeyLabelFontSize,
      sankeyLabelRotate: slotConfig.sankeyLabelRotate,
      sankeyEmphasisFocus: slotConfig.sankeyEmphasisFocus,
      sankeyLevelLabelFormats: slotConfig.sankeyLevelLabelFormats,
      sankeyLevelNodeGaps: slotConfig.sankeyLevelNodeGaps,
      sankeyLevelLabelDistances: slotConfig.sankeyLevelLabelDistances,
      sankeyLevelNodeWidths: slotConfig.sankeyLevelNodeWidths,
      sankeyLevelPathFilters: slotConfig.sankeyLevelPathFilters,
      sankeySort: slotConfig.sankeySort,
      sankeyPinUnstatedToBottom: slotConfig.sankeyPinUnstatedToBottom,
      sankeyFlowConservation: slotConfig.sankeyFlowConservation,
      sankeyLevelNodeOrders: slotConfig.sankeyLevelNodeOrders,
      levelSegmentIndices: slotConfig.levelSegmentIndices,
      levelScopeFilters: slotConfig.levelScopeFilters,
      sankeyLabelLineHeight: slotConfig.sankeyLabelLineHeight,
      sankeyLabelFontWeight: slotConfig.sankeyLabelFontWeight,
      sankeyLabelColor: slotConfig.sankeyLabelColor,
      bubbleScale: slotConfig.bubbleScale,
      gaugeMaxScale: slotConfig.gaugeMaxScale,
      sunburstLevelConfigs: slotConfig.sunburstLevelConfigs,
      sunburstSort: slotConfig.sunburstSort,
      sunburstNodeClick: slotConfig.sunburstNodeClick,
      sunburstEmphasisFocus: slotConfig.sunburstEmphasisFocus,
      barSorting: slotConfig.barSorting,
      barOrientation: slotConfig.barOrientation || 'horizontal',
      barThickness: slotConfig.barThickness,
      barBorderRadius: slotConfig.barBorderRadius,
      barGap: slotConfig.barGap,
      barClusterGap: slotConfig.barClusterGap ?? 20,
      barInnerGap: slotConfig.barInnerGap ?? 15,
      enableErrorBars: slotConfig.enableErrorBars ?? false,
      errorBarType: slotConfig.errorBarType || 'std_error',
      enableHatchPatterns: slotConfig.enableHatchPatterns ?? false,
      axisScaleType: slotConfig.axisScaleType || 'linear',
      axisTickDirection: slotConfig.axisTickDirection || 'outside',
      showAxisBaseline: slotConfig.showAxisBaseline ?? true,
      customAxisTitleX: slotConfig.customAxisTitleX || '',
      customAxisTitleY: slotConfig.customAxisTitleY || '',
      showAxisTitleX: slotConfig.showAxisTitleX ?? true,
      showAxisTitleY: slotConfig.showAxisTitleY ?? true,
      axisTitleFontSizeX: slotConfig.axisTitleFontSizeX ?? 11,
      axisTitleFontSizeY: slotConfig.axisTitleFontSizeY ?? 11,
      axisTitleFontWeightX: slotConfig.axisTitleFontWeightX || 'bold',
      axisTitleFontWeightY: slotConfig.axisTitleFontWeightY || 'bold',
      axisTitleFontStyleX: slotConfig.axisTitleFontStyleX || 'normal',
      axisTitleFontStyleY: slotConfig.axisTitleFontStyleY || 'normal',
      axisTitleColorX: slotConfig.axisTitleColorX || '',
      axisTitleColorY: slotConfig.axisTitleColorY || '',
      axisTitleLocationX: slotConfig.axisTitleLocationX || 'middle',
      axisTitleLocationY: slotConfig.axisTitleLocationY || 'middle',
      axisTitleGapX: slotConfig.axisTitleGapX ?? 28,
      axisTitleGapY: slotConfig.axisTitleGapY ?? 38,
      axisTitleRotateX: slotConfig.axisTitleRotateX ?? 0,
      axisTitleRotateY: slotConfig.axisTitleRotateY ?? 90,
      axisTitleAlignX: slotConfig.axisTitleAlignX || 'center',
      axisTitleAlignY: slotConfig.axisTitleAlignY || 'center',
      axisTitleOffsetX_X: slotConfig.axisTitleOffsetX_X ?? 0,
      axisTitleOffsetY_X: slotConfig.axisTitleOffsetY_X ?? 0,
      axisTitleOffsetX_Y: slotConfig.axisTitleOffsetX_Y ?? 0,
      axisTitleOffsetY_Y: slotConfig.axisTitleOffsetY_Y ?? 0,
      axisTitlePrefixX: slotConfig.axisTitlePrefixX || '',
      axisTitleSuffixX: slotConfig.axisTitleSuffixX || '',
      axisTitlePrefixY: slotConfig.axisTitlePrefixY || '',
      axisTitleSuffixY: slotConfig.axisTitleSuffixY || '',
      showAxisLabelX: slotConfig.showAxisLabelX ?? true,
      showAxisLabelY: slotConfig.showAxisLabelY ?? true,
      axisLabelFontSizeX: slotConfig.axisLabelFontSizeX ?? 11,
      axisLabelFontSizeY: slotConfig.axisLabelFontSizeY ?? 11,
      axisLabelFontWeightX: slotConfig.axisLabelFontWeightX || 'normal',
      axisLabelFontWeightY: slotConfig.axisLabelFontWeightY || 'normal',
      axisLabelFontStyleX: slotConfig.axisLabelFontStyleX || 'normal',
      axisLabelFontStyleY: slotConfig.axisLabelFontStyleY || 'normal',
      axisLabelColorX: slotConfig.axisLabelColorX || '',
      axisLabelColorY: slotConfig.axisLabelColorY || '',
      axisLabelRotateX: slotConfig.axisLabelRotateX ?? 0,
      axisLabelRotateY: slotConfig.axisLabelRotateY ?? 0,
      axisLabelMarginX: slotConfig.axisLabelMarginX ?? 8,
      axisLabelMarginY: slotConfig.axisLabelMarginY ?? 8,
      axisLabelOverflowX: slotConfig.axisLabelOverflowX || 'none',
      axisLabelOverflowY: slotConfig.axisLabelOverflowY || 'none',
      axisLabelWidthX: slotConfig.axisLabelWidthX ?? 120,
      axisLabelWidthY: slotConfig.axisLabelWidthY ?? 140,
      axisLabelLineHeightX: slotConfig.axisLabelLineHeightX ?? 14,
      axisLabelLineHeightY: slotConfig.axisLabelLineHeightY ?? 14,
      axisLabelFormatX: slotConfig.axisLabelFormatX || 'auto',
      axisLabelFormatY: slotConfig.axisLabelFormatY || 'auto',
      axisLabelPrefixX: slotConfig.axisLabelPrefixX || '',
      axisLabelSuffixX: slotConfig.axisLabelSuffixX || '',
      axisLabelPrefixY: slotConfig.axisLabelPrefixY || '',
      axisLabelSuffixY: slotConfig.axisLabelSuffixY || '',
      axisLabelIntervalX: slotConfig.axisLabelIntervalX ?? 'auto',
      axisLabelIntervalY: slotConfig.axisLabelIntervalY ?? 'auto',
      axisLabelDecimalsX: slotConfig.axisLabelDecimalsX,
      axisLabelDecimalsY: slotConfig.axisLabelDecimalsY,
      showGridLinesX: slotConfig.showGridLinesX ?? false,
      showGridLinesY: slotConfig.showGridLinesY ?? true,
      gridLineStyle: slotConfig.gridLineStyle || 'dashed',
      gridLineColor: slotConfig.gridLineColor || '',
      gridLineOpacity: slotConfig.gridLineOpacity ?? 100,
      labelFormat: slotConfig.labelFormat || style.defaultLabelFormat || 'ratio_percent',
      barLabelPosition: slotConfig.barLabelPosition,
      barLabelFormat: slotConfig.barLabelFormat || style.defaultLabelFormat || 'ratio_percent',
      barYAxisWidth: slotConfig.barYAxisWidth,
      barYAxisOverflow: slotConfig.barYAxisOverflow,
      barLineHeight: slotConfig.barLineHeight ?? 14,
      barYAxisFontSize: slotConfig.barYAxisFontSize ?? 11,
      barYAxisFontWeight: slotConfig.barYAxisFontWeight,
      barYAxisFontStyle: slotConfig.barYAxisFontStyle,
      barYAxisColor: slotConfig.barYAxisColor,
      barBenchmarkLine: slotConfig.barBenchmarkLine,
      barBenchmarkValue: slotConfig.barBenchmarkValue,
      barBenchmarkLabel: slotConfig.barBenchmarkLabel,
      barBenchmarkStyle: slotConfig.barBenchmarkStyle,
      barBenchmarkColor: slotConfig.barBenchmarkColor,
      legendFormat: slotConfig.legendFormat || style.defaultLegendFormat || 'name',
      barLegendFormat: slotConfig.barLegendFormat || style.defaultLegendFormat || 'name',
      barLegendPosition: slotConfig.barLegendPosition,
      legendContextScope: slotConfig.legendContextScope,
      syncLegendAndBarMetrics: slotConfig.syncLegendAndBarMetrics,
      barLabelContextScope: slotConfig.barLabelContextScope,
      legendShowParentPrefix: slotConfig.legendShowParentPrefix,
      legendParentPrefixStyle: slotConfig.legendParentPrefixStyle,
      legendGroupByParent: slotConfig.legendGroupByParent,
      decimalPrecision: style.decimalPrecision,
      useTildeForCoarse: style.useTildeForCoarse,
      ratioStyle: style.ratioStyle,
      forceCohortDenominator: style.forceCohortDenominator,
      chartScale: camera.chartScale,
      panX: camera.panX,
      panY: camera.panY,
      tiltAngle: camera.tiltAngle,
      rotationAngle: camera.rotationAngle,
      fitOffsetX: camera.fitOffsetX,
      fitOffsetY: camera.fitOffsetY,
      containerPadding: camera.containerPadding,
      sunburstLegendLevel: slotConfig.sunburstLegendLevel,
      sunburstLegendFormat: slotConfig.sunburstLegendFormat || style.defaultLegendFormat || 'name',
      sunburstLegendPosition: slotConfig.sunburstLegendPosition,
      levelCustomGroups: slotConfig.levelCustomGroups,
      levelCustomGroupLinks: slotConfig.levelCustomGroupLinks,
      levelTargetFields: slotConfig.levelTargetFields,
      primaryScopeFilter: slotConfig.primaryScopeFilter,
      secondaryScopeFilter: slotConfig.secondaryScopeFilter,
      customCategoryMap: slotConfig.customCategoryMap,
      enableManualOverrides: slotConfig.enableManualOverrides,
      manualCategoryValues: slotConfig.manualCategoryValues,
      customSliceColors: slotConfig.customSliceColors,
      pieLabelPlacement: slotConfig.pieLabelPlacement,
      pieRadiusRatio: slotConfig.pieRadiusRatio,
      pieLabelWidth: slotConfig.pieLabelWidth,
      pieLeaderLineLength: slotConfig.pieLeaderLineLength,
      pieLeaderLineLength2: slotConfig.pieLeaderLineLength2,
      pieLabelDistance: slotConfig.pieLabelDistance,
      pieLineHeight: slotConfig.pieLineHeight,
      barLabelDistance: slotConfig.barLabelDistance,
      barLabelFontSize: slotConfig.barLabelFontSize,
      barLabelFontWeight: slotConfig.barLabelFontWeight,
      barLabelFontStyle: slotConfig.barLabelFontStyle,
      barLabelColor: slotConfig.barLabelColor,
      barLabelRotate: slotConfig.barLabelRotate,
      barLabelShowZero: slotConfig.barLabelShowZero,
      barLabelMinThreshold: slotConfig.barLabelMinThreshold,
      barLabelLineHeight: slotConfig.barLabelLineHeight,
      barLabelDecimals: slotConfig.barLabelDecimals,
      barValueCeiling: slotConfig.barValueCeiling,
      barValueInterval: slotConfig.barValueInterval,
      legendDistance: slotConfig.legendDistance,
      legendWidth: slotConfig.legendWidth,
      legendWrapWidth: slotConfig.legendWrapWidth,
      legendLineHeight: slotConfig.legendLineHeight,
      legendItemGap: slotConfig.legendItemGap,
      legendFontSize: slotConfig.legendFontSize,
      legendFontFamily: slotConfig.legendFontFamily,
      legendFontStyle: slotConfig.legendFontStyle,
      legendLetterSpacing: slotConfig.legendLetterSpacing,
      legendOverflow: slotConfig.legendOverflow,
      umbrellanizerMap,
      lineMode: slotConfig.lineMode,
      lineTimeSteps: slotConfig.lineTimeSteps,
      lineTimeStepIntervalName: slotConfig.lineTimeStepIntervalName,
      lineYAxisTitle: slotConfig.lineYAxisTitle,
      lineYMin: slotConfig.lineYMin,
      lineYMax: slotConfig.lineYMax,
      lineBaselineA: slotConfig.lineBaselineA,
      lineBaselineB: slotConfig.lineBaselineB,
      lineBaselineName: slotConfig.lineBaselineName,
      lineBaselineColor: slotConfig.lineBaselineColor,
      lineBaselineStyle: slotConfig.lineBaselineStyle,
      lineEstimatorInitial: slotConfig.lineEstimatorInitial,
      lineEstimatorDrift: slotConfig.lineEstimatorDrift,
      lineEstimatorModulation: slotConfig.lineEstimatorModulation,
      lineEstimatorName: slotConfig.lineEstimatorName,
      lineEstimatorColor: slotConfig.lineEstimatorColor,
      lineEstimatorStyle: slotConfig.lineEstimatorStyle,
      lineThresholdValue: slotConfig.lineThresholdValue,
      lineThresholdName: slotConfig.lineThresholdName,
      lineThresholdLabel: slotConfig.lineThresholdLabel,
      lineThresholdColor: slotConfig.lineThresholdColor,
      lineThresholdStyle: slotConfig.lineThresholdStyle,
      lineThresholdPosition: slotConfig.lineThresholdPosition,
      lineThresholdLineWidth: slotConfig.lineThresholdLineWidth,
      lineAxisPointerType: slotConfig.lineAxisPointerType,
      lineMarkerSymbol: slotConfig.lineMarkerSymbol,
      lineXAxisInterval: slotConfig.lineXAxisInterval,
      lineShowGridLines: slotConfig.lineShowGridLines,
      lineGridLeft: slotConfig.lineGridLeft,
      lineGridRight: slotConfig.lineGridRight,
      lineGridTop: slotConfig.lineGridTop,
      lineGridBottom: slotConfig.lineGridBottom,
      lineWidth: slotConfig.lineWidth,
      showLineMarkers: slotConfig.showLineMarkers,
      lineMarkerSize: slotConfig.lineMarkerSize,
      lineAreaOpacity: slotConfig.lineAreaOpacity,
      lineBaselineAreaOpacity: slotConfig.lineBaselineAreaOpacity,
      lineEstimatorAreaOpacity: slotConfig.lineEstimatorAreaOpacity,
      lineBaselineFillMode: slotConfig.lineBaselineFillMode,
      lineEstimatorFillMode: slotConfig.lineEstimatorFillMode,
      lineShowTxEvents: slotConfig.lineShowTxEvents,
      lineTxEventSymbol: slotConfig.lineTxEventSymbol,
      lineTxEventColor: slotConfig.lineTxEventColor,
      lineTxEventSize: slotConfig.lineTxEventSize,
      lineShowTxLabels: slotConfig.lineShowTxLabels,
      lineTxEventLabel: slotConfig.lineTxEventLabel,
      lineTxEventSeriesName: slotConfig.lineTxEventSeriesName,
      lineStepMode: slotConfig.lineStepMode,
      roseType: slotConfig.roseType,
      piePadAngle: slotConfig.piePadAngle,
      pieCornerRadius: slotConfig.pieCornerRadius,
      pieSort: slotConfig.pieSort,
      pieStartAngle: slotConfig.pieStartAngle,
      pieMinAngle: slotConfig.pieMinAngle,
      treemapAlgorithm: slotConfig.treemapAlgorithm,
      treemapSquareRatio: slotConfig.treemapSquareRatio,
      treemapVisibleDepth: slotConfig.treemapVisibleDepth,
      treemapGapWidth: slotConfig.treemapGapWidth,
      treemapBorderWidth: slotConfig.treemapBorderWidth,
      treemapBorderRadius: slotConfig.treemapBorderRadius,
      treemapBorderColorMode: slotConfig.treemapBorderColorMode,
      treemapBorderColor: slotConfig.treemapBorderColor,
      treemapNodeClick: slotConfig.treemapNodeClick,
      treemapRoam: slotConfig.treemapRoam,
      treemapDrillDownIcon: slotConfig.treemapDrillDownIcon,
      treemapShowBreadcrumb: slotConfig.treemapShowBreadcrumb,
      treemapBreadcrumbPosition: slotConfig.treemapBreadcrumbPosition,
      treemapBreadcrumbHeight: slotConfig.treemapBreadcrumbHeight,
      treemapColorMode: slotConfig.treemapColorMode,
      treemapCohortMode: slotConfig.treemapCohortMode,
      treemapColorMappingBy: slotConfig.treemapColorMappingBy,
      treemapColorAlphaMin: slotConfig.treemapColorAlphaMin,
      treemapColorAlphaMax: slotConfig.treemapColorAlphaMax,
      treemapColorSaturationMin: slotConfig.treemapColorSaturationMin,
      treemapColorSaturationMax: slotConfig.treemapColorSaturationMax,
      treemapShowLabels: slotConfig.treemapShowLabels,
      treemapLabelPosition: slotConfig.treemapLabelPosition,
      treemapLabelFormat: slotConfig.treemapLabelFormat,
      treemapLabelFontSize: slotConfig.treemapLabelFontSize,
      treemapLabelFontWeight: slotConfig.treemapLabelFontWeight,
      treemapLabelFontStyle: slotConfig.treemapLabelFontStyle,
      treemapLabelColorMode: slotConfig.treemapLabelColorMode,
      treemapLabelColor: slotConfig.treemapLabelColor,
      treemapLabelOverflow: slotConfig.treemapLabelOverflow,
      treemapLabelWidth: slotConfig.treemapLabelWidth,
      treemapLabelLineHeight: slotConfig.treemapLabelLineHeight,
      treemapShowUpperLabel: slotConfig.treemapShowUpperLabel,
      treemapUpperLabelHeight: slotConfig.treemapUpperLabelHeight,
      treemapUpperLabelWidth: slotConfig.treemapUpperLabelWidth,
      treemapUpperLabelPosition: slotConfig.treemapUpperLabelPosition,
      treemapUpperLabelFormat: slotConfig.treemapUpperLabelFormat,
      treemapUpperLabelFontSize: slotConfig.treemapUpperLabelFontSize,
      treemapUpperLabelFontWeight: slotConfig.treemapUpperLabelFontWeight,
      treemapUpperLabelColorMode: slotConfig.treemapUpperLabelColorMode,
      treemapUpperLabelColor: slotConfig.treemapUpperLabelColor,
      treemapUpperLabelBgColor: slotConfig.treemapUpperLabelBgColor,
      treemapVisibleMin: slotConfig.treemapVisibleMin,
      treemapChildrenVisibleMin: slotConfig.treemapChildrenVisibleMin,
      treemapLevelConfigs: slotConfig.treemapLevelConfigs,
      sunburstColorMode: slotConfig.sunburstColorMode,
      heatmapCellRadius: slotConfig.heatmapCellRadius,
      heatmapColorPreset: slotConfig.heatmapColorPreset,
      radarShape: slotConfig.radarShape,
      radarStartAngle: slotConfig.radarStartAngle,
      radarAreaOpacity: slotConfig.radarAreaOpacity,
      radarLineWidth: slotConfig.radarLineWidth,
      radarSplitNumber: slotConfig.radarSplitNumber,
      radarRadius: slotConfig.radarRadius,
      radarCenterX: slotConfig.radarCenterX,
      radarCenterY: slotConfig.radarCenterY,
      radarAxisLine: slotConfig.radarAxisLine,
      radarAxisLineWidth: slotConfig.radarAxisLineWidth,
      radarAxisLineType: slotConfig.radarAxisLineType,
      radarAxisLineColor: slotConfig.radarAxisLineColor,
      radarAxisLineOpacity: slotConfig.radarAxisLineOpacity,
      radarSplitLine: slotConfig.radarSplitLine,
      radarSplitLineWidth: slotConfig.radarSplitLineWidth,
      radarSplitLineType: slotConfig.radarSplitLineType,
      radarSplitLineColor: slotConfig.radarSplitLineColor,
      radarSplitLineOpacity: slotConfig.radarSplitLineOpacity,
      radarSplitArea: slotConfig.radarSplitArea,
      radarSplitAreaTheme: slotConfig.radarSplitAreaTheme,
      radarSplitAreaOpacity: slotConfig.radarSplitAreaOpacity,
      radarSplitAreaColor1: slotConfig.radarSplitAreaColor1,
      radarSplitAreaColor2: slotConfig.radarSplitAreaColor2,
      radarShowAxisScaleLabels: slotConfig.radarShowAxisScaleLabels,
      radarAxisScaleFormat: slotConfig.radarAxisScaleFormat,
      radarAxisScaleFontSize: slotConfig.radarAxisScaleFontSize,
      radarAxisScaleFontWeight: slotConfig.radarAxisScaleFontWeight,
      radarAxisScaleColor: slotConfig.radarAxisScaleColor,
      radarScaleMax: slotConfig.radarScaleMax,
      radarScaleMin: slotConfig.radarScaleMin,
      radarShowAxisTicks: slotConfig.radarShowAxisTicks,
      radarAxisNameMargin: slotConfig.radarAxisNameMargin,
      radarAxisNameWidth: slotConfig.radarAxisNameWidth,
      radarAxisNameOverflow: slotConfig.radarAxisNameOverflow,
      radarAxisNameLineHeight: slotConfig.radarAxisNameLineHeight,
      radarAxisNameBgColor: slotConfig.radarAxisNameBgColor,
      radarAxisNamePadding: slotConfig.radarAxisNamePadding,
      radarAxisNameBorderRadius: slotConfig.radarAxisNameBorderRadius,
      radarAxisNameBorderColor: slotConfig.radarAxisNameBorderColor,
      radarAxisNameBorderWidth: slotConfig.radarAxisNameBorderWidth,
      radarShowDataLabels: slotConfig.radarShowDataLabels,
      radarDataLabelPosition: slotConfig.radarDataLabelPosition,
      radarDataLabelFontSize: slotConfig.radarDataLabelFontSize,
      radarDataLabelFontWeight: slotConfig.radarDataLabelFontWeight,
      radarDataLabelColor: slotConfig.radarDataLabelColor,
      radarDataLabelFormat: slotConfig.radarDataLabelFormat,
      radarSmooth: slotConfig.radarSmooth,
      radarBaselineLineStyle: slotConfig.radarBaselineLineStyle,
      radarBaselineSymbol: slotConfig.radarBaselineSymbol,
      radarBaselineSymbolSize: slotConfig.radarBaselineSymbolSize,
      radarBaselineAreaColor: slotConfig.radarBaselineAreaColor,
      radarBaselineSymbolBorderColor: slotConfig.radarBaselineSymbolBorderColor,
      radarBaselineSymbolBorderWidth: slotConfig.radarBaselineSymbolBorderWidth,
      radarMode: slotConfig.radarMode,
      radarVariables: slotConfig.radarVariables,
      radarVariableAliases: slotConfig.radarVariableAliases,
      radarVariableTargets: slotConfig.radarVariableTargets,
      radarIndicatorFormat: slotConfig.radarIndicatorFormat,
      radarShowTarget: slotConfig.radarShowTarget,
      radarTargetName: slotConfig.radarTargetName,
      radarTargetValue: slotConfig.radarTargetValue,
      radarTargetLineStyle: slotConfig.radarTargetLineStyle,
      radarTargetLineWidth: slotConfig.radarTargetLineWidth,
      radarTargetColor: slotConfig.radarTargetColor,
      radarTargetAreaOpacity: slotConfig.radarTargetAreaOpacity,
      radarTargetSmooth: slotConfig.radarTargetSmooth,
      radarTargetSymbol: slotConfig.radarTargetSymbol,
      radarTargetSymbolSize: slotConfig.radarTargetSymbolSize,
      radarBaselineName: slotConfig.radarBaselineName,
      radarBaselineColor: slotConfig.radarBaselineColor,
      radarTagShareName: slotConfig.radarTagShareName,
      radarTagShareColor: slotConfig.radarTagShareColor,
      radarTagShareLineStyle: slotConfig.radarTagShareLineStyle,
      radarTagShareLineWidth: slotConfig.radarTagShareLineWidth,
      radarTagShareAreaOpacity: slotConfig.radarTagShareAreaOpacity,
      radarTagShareSmooth: slotConfig.radarTagShareSmooth,
      radarTagShareSymbol: slotConfig.radarTagShareSymbol,
      radarTagShareSymbolSize: slotConfig.radarTagShareSymbolSize,
      funnelAlign: slotConfig.funnelAlign,
      funnelGap: slotConfig.funnelGap,
      funnelNeckWidth: slotConfig.funnelNeckWidth,
      funnelNeckHeight: slotConfig.funnelNeckHeight,
      funnelLabelPosition: slotConfig.funnelLabelPosition,
      funnelSort: slotConfig.funnelSort,
      boxplotBoxWidth: slotConfig.boxplotBoxWidth,
      boxplotShowScatter: slotConfig.boxplotShowScatter,
      boxplotOrientation: slotConfig.boxplotOrientation,
      boxplotFillColor: slotConfig.boxplotFillColor,
      boxplotBorderColor: slotConfig.boxplotBorderColor,
      scatterPointSize: slotConfig.scatterPointSize,
      scatterPointOpacity: slotConfig.scatterPointOpacity,
      scatterShowRegression: slotConfig.scatterShowRegression,
      scatterRegressionType: slotConfig.scatterRegressionType,
      bubbleMode: slotConfig.bubbleMode,
      bubbleMinRadius: slotConfig.bubbleMinRadius,
      bubbleMaxRadius: slotConfig.bubbleMaxRadius,
      bubbleOpacity: slotConfig.bubbleOpacity,
      bubbleBorderWidth: slotConfig.bubbleBorderWidth,
      bubbleBorderColor: slotConfig.bubbleBorderColor,
      bubbleShowLabels: slotConfig.bubbleShowLabels,
      bubbleLabelFormat: slotConfig.bubbleLabelFormat,
      bubbleLabelFontSize: slotConfig.bubbleLabelFontSize,
      bubbleLabelColor: slotConfig.bubbleLabelColor,
      bubbleColorMode: slotConfig.bubbleColorMode,
      bubbleShowGridLines: slotConfig.bubbleShowGridLines,
      bubbleComplianceRules: slotConfig.bubbleComplianceRules,
      bubbleXAxisName: slotConfig.bubbleXAxisName,
      bubbleYAxisName: slotConfig.bubbleYAxisName,
      bubbleXAxisNameGap: slotConfig.bubbleXAxisNameGap,
      bubbleYAxisNameGap: slotConfig.bubbleYAxisNameGap,
      bubbleXAxisNameLocation: slotConfig.bubbleXAxisNameLocation,
      bubbleYAxisNameLocation: slotConfig.bubbleYAxisNameLocation,
      bubbleAxisTitleFontSize: slotConfig.bubbleAxisTitleFontSize,
      bubbleAxisTitleFontWeight: slotConfig.bubbleAxisTitleFontWeight,
      bubbleAxisTitleColor: slotConfig.bubbleAxisTitleColor,
      bubbleGridLeft: slotConfig.bubbleGridLeft,
      bubbleGridBottom: slotConfig.bubbleGridBottom,
      bubbleGridTop: slotConfig.bubbleGridTop,
      bubbleGridRight: slotConfig.bubbleGridRight,
      bubbleSeriesName: slotConfig.bubbleSeriesName,
      bubbleLegendMode: slotConfig.bubbleLegendMode,
      graphRepulsion: slotConfig.graphRepulsion,
      graphEdgeLength: slotConfig.graphEdgeLength,
      graphGravity: slotConfig.graphGravity,
      graphCurveness: slotConfig.graphCurveness,
      graphShowLinkWeights: slotConfig.graphShowLinkWeights,
      graphNodeSize: slotConfig.graphNodeSize,
      graphDraggable: slotConfig.graphDraggable,
      gaugeStartAngle: slotConfig.gaugeStartAngle,
      gaugeEndAngle: slotConfig.gaugeEndAngle,
      gaugePointerWidth: slotConfig.gaugePointerWidth,
      gaugeDialWidth: slotConfig.gaugeDialWidth,
      gaugeUnit: slotConfig.gaugeUnit,
      gaugeSplitNumber: slotConfig.gaugeSplitNumber,
      calendarCellSize: slotConfig.calendarCellSize,
      calendarYear: slotConfig.calendarYear,
      calendarColorPreset: slotConfig.calendarColorPreset,
      stackedNormalized: slotConfig.stackedNormalized,
      stackedReverseOrder: slotConfig.stackedReverseOrder,
      stackedPerBarSorting: slotConfig.stackedPerBarSorting,
      stackedShowTotalLabel: slotConfig.stackedShowTotalLabel,
      stackedTotalLabelPosition: slotConfig.stackedTotalLabelPosition,
      stackedTotalLabelFormat: slotConfig.stackedTotalLabelFormat,
      stackedTotalFontSize: slotConfig.stackedTotalFontSize,
      stackedTotalFontWeight: slotConfig.stackedTotalFontWeight,
      stackedTotalColor: slotConfig.stackedTotalColor,
      stackedTotalLabelDistance: slotConfig.stackedTotalLabelDistance,
      legendType: slotConfig.legendType,
      legendAlign: slotConfig.legendAlign,
      legendIcon: slotConfig.legendIcon,
      legendItemWidth: slotConfig.legendItemWidth,
      legendItemHeight: slotConfig.legendItemHeight,
      legendFontWeight: slotConfig.legendFontWeight,
      legendTextColor: slotConfig.legendTextColor,
      legendBackgroundColor: slotConfig.legendBackgroundColor,
      legendBorderColor: slotConfig.legendBorderColor,
      legendBorderWidth: slotConfig.legendBorderWidth,
      legendBorderRadius: slotConfig.legendBorderRadius,
      legendPadding: slotConfig.legendPadding,
      scatterAxisTitle: slotConfig.scatterAxisTitle,
      scatterAxisMin: slotConfig.scatterAxisMin,
      scatterAxisMax: slotConfig.scatterAxisMax,
      scatterAxisInterval: slotConfig.scatterAxisInterval,
      scatterSeriesName: slotConfig.scatterSeriesName,
      barSeriesName: slotConfig.barSeriesName,
      scatterSymbol: slotConfig.scatterSymbol,
      scatterSymbolSize: slotConfig.scatterSymbolSize,
      scatterColor: slotConfig.scatterColor,
      scatterBorderColor: slotConfig.scatterBorderColor,
      scatterBorderWidth: slotConfig.scatterBorderWidth,
      scatterValues: slotConfig.scatterValues,
      scatterAxisNameGap: slotConfig.scatterAxisNameGap,
      scatterShowDataLabels: slotConfig.scatterShowDataLabels,
      scatterLabelPosition: slotConfig.scatterLabelPosition,
      scatterLabelFontSize: slotConfig.scatterLabelFontSize,
      scatterLabelFontWeight: slotConfig.scatterLabelFontWeight,
      scatterLabelFontStyle: slotConfig.scatterLabelFontStyle,
      scatterLabelColor: slotConfig.scatterLabelColor,
      scatterLabelDistance: slotConfig.scatterLabelDistance,
      scatterLabelLineHeight: slotConfig.scatterLabelLineHeight,
      lineLabelFontSize: slotConfig.lineLabelFontSize,
      lineLabelFontWeight: slotConfig.lineLabelFontWeight,
      lineLabelFontStyle: slotConfig.lineLabelFontStyle,
      lineLabelColor: slotConfig.lineLabelColor,
      pieLabelFontWeight: slotConfig.pieLabelFontWeight,
      pieLabelFontStyle: slotConfig.pieLabelFontStyle,
      pieLabelColor: slotConfig.pieLabelColor,
      radarLabelFontSize: slotConfig.radarLabelFontSize,
      radarLabelFontWeight: slotConfig.radarLabelFontWeight,
      radarLabelFontStyle: slotConfig.radarLabelFontStyle,
      radarLabelColor: slotConfig.radarLabelColor,
      radarAxisNameFontSize: slotConfig.radarAxisNameFontSize ?? slotConfig.radarLabelFontSize,
      radarAxisNameFontWeight: slotConfig.radarAxisNameFontWeight ?? slotConfig.radarLabelFontWeight,
      radarAxisNameFontStyle: slotConfig.radarAxisNameFontStyle ?? slotConfig.radarLabelFontStyle,
      radarAxisNameColor: slotConfig.radarAxisNameColor ?? slotConfig.radarLabelColor,
      heatmapLabelFontSize: slotConfig.heatmapLabelFontSize,
      heatmapLabelFontWeight: slotConfig.heatmapLabelFontWeight,
      heatmapLabelFontStyle: slotConfig.heatmapLabelFontStyle,
      heatmapLabelColor: slotConfig.heatmapLabelColor,
      funnelLabelFontSize: slotConfig.funnelLabelFontSize,
      funnelLabelFontWeight: slotConfig.funnelLabelFontWeight,
      funnelLabelFontStyle: slotConfig.funnelLabelFontStyle,
      funnelLabelColor: slotConfig.funnelLabelColor,
      boxplotLabelFontSize: slotConfig.boxplotLabelFontSize,
      boxplotLabelFontWeight: slotConfig.boxplotLabelFontWeight,
      boxplotLabelFontStyle: slotConfig.boxplotLabelFontStyle,
      boxplotLabelColor: slotConfig.boxplotLabelColor,
      bubbleLabelFontWeight: slotConfig.bubbleLabelFontWeight,
      bubbleLabelFontStyle: slotConfig.bubbleLabelFontStyle,
      barColorCustom: slotConfig.barColorCustom,
      barGridTop: slotConfig.barGridTop,
      barGridBottom: slotConfig.barGridBottom,
      barGridLeft: slotConfig.barGridLeft,
      barGridRight: slotConfig.barGridRight,
      scatterSortMode: slotConfig.scatterSortMode,
      otherCategoryLabel: slotConfig.otherCategoryLabel,
      // Universal Layout Margins & Canvas Padding
      gridMarginAuto: slotConfig.gridMarginAuto,
      gridMarginTop: slotConfig.gridMarginTop,
      gridMarginBottom: slotConfig.gridMarginBottom,
      gridMarginLeft: slotConfig.gridMarginLeft,
      gridMarginRight: slotConfig.gridMarginRight,
      // Universal Data Label Styling
      universalLabelPosition: slotConfig.universalLabelPosition,
      universalLabelDistance: slotConfig.universalLabelDistance,
      universalLabelOverflow: slotConfig.universalLabelOverflow,
      universalMaxLabelWidth: slotConfig.universalMaxLabelWidth,
      universalLabelLineHeight: slotConfig.universalLabelLineHeight,
      universalLabelFontSize: slotConfig.universalLabelFontSize,
      universalLabelFontWeight: slotConfig.universalLabelFontWeight,
      universalLabelFontStyle: slotConfig.universalLabelFontStyle,
      universalLabelColor: slotConfig.universalLabelColor,
      universalLabelColorMode: slotConfig.universalLabelColorMode,
      universalLabelRotate: slotConfig.universalLabelRotate,
      universalLabelMinThreshold: slotConfig.universalLabelMinThreshold,
      universalLabelShowZero: slotConfig.universalLabelShowZero,
      // Smart Color Modes & Interactive Propagation
      smartColorMode: slotConfig.smartColorMode,
      smartColorPropagation: slotConfig.smartColorPropagation,
      ...overrides
    });
  }, [config.slotsConfig, config.currentSlotConfig, layout.layoutMode, activePapers, style, camera, umbrellanizerMap]);

  const canvas = useChartCanvas({
    isOpen,
    currentStep: config.currentStep,
    layoutMode: layout.layoutMode,
    activeSlotsList: layout.activeSlotsList,
    activeSlot: layout.activeSlot,
    themePreset: style.themePreset,
    fontFamily: style.fontFamily,
    fontSize: style.fontSize,
    chartTitle: style.chartTitle,
    chartSubtitle: style.chartSubtitle,
    showChartTitle: style.showChartTitle,
    showChartSubtitle: style.showChartSubtitle,
    titleFontSize: style.titleFontSize,
    titleFontWeight: style.titleFontWeight,
    titleFontStyle: style.titleFontStyle,
    titleColor: style.titleColor,
    titleAlign: style.titleAlign,
    subtitleFontSize: style.subtitleFontSize,
    subtitleFontWeight: style.subtitleFontWeight,
    subtitleFontStyle: style.subtitleFontStyle,
    subtitleColor: style.subtitleColor,
    subtitleLineHeight: style.subtitleLineHeight,
    titleGap: style.titleGap,
    subfigureLabelStyle: style.subfigureLabelStyle,
    subfigureLabelFontSize: style.subfigureLabelFontSize,
    subfigureLabelFontWeight: style.subfigureLabelFontWeight,
    panelGutter: style.panelGutter,
    showPanelBorders: style.showPanelBorders,
    aspectRatio: style.aspectRatio,
    customWidth: style.customWidth,
    customHeight: style.customHeight,
    dimensionUnit: style.dimensionUnit,
    slotsConfig: config.slotsConfig,
    chartScale: camera.chartScale,
    panX: camera.panX,
    panY: camera.panY,
    tiltAngle: camera.tiltAngle,
    rotationAngle: camera.rotationAngle,
    fitOffsetX: camera.fitOffsetX,
    fitOffsetY: camera.fitOffsetY,
    containerPadding: camera.containerPadding,
    inspectedSlot: workspace.inspectedSlot,
    generateSlotOption
  });

  const value: VisualizerContextValue = useMemo(() => ({
    props,
    layout,
    config,
    data,
    style,
    camera,
    workspace,
    presets,
    canvas,
    generateSlotOption
  }), [props, layout, config, data, style, camera, workspace, presets, canvas, generateSlotOption]);

  return (
    <VisualizerContext.Provider value={value}>
      {children}
    </VisualizerContext.Provider>
  );
}
